### ISSUE TITLE
Comments of type "* ... ;" not registering after macro call

### ISSUE THREAD

**Issue by pecan-pine** [sassoftware/vscode-sas-extension#10]
In this example:

`%run_this_macro()
*comment that doesn't get highlighted;
`

the comment doesn't get highlighted. Also, quotes in comments of this type sometimes aren't masked (i.e. the "t get highlighted" in the example above will be highlighted as a string, as well as following characters) -- I haven't been able to tell when exactly this happens, though. 

The comment is highlighted properly if a semicolon is added, as in 

`%run_this_macro();
*this gets highlighted;
`

Since the semicolon is not necessary after macro calls in SAS, I believe these comments should be highlighted independent of whether a semicolon is used or not.

**Comment by scnwwu** [comment]
A macro call is not a statement so doesn't require semicolon. It can be embedded in a statement. An end of a macro call doesn't imply an end of a statement.
Comment statement must be a separate statement. It's documented [here](https://go.documentation.sas.com/doc/en/pgmsascdc/v_027/lestmtsglobal/n1v51exifva71an1cvfn2z6j26lo.htm#n01vkze93ddgpnn1q89rby429gd0)
Restrictions: These comments must be written as separate statements.

**Comment by pecan-pine** [comment]
Is this expected behavior, then? In the program editor in base SAS it highlights this case as a comment:

`%run_this_macro() *this is highlighted as a comment in base SAS;`

**Comment by scnwwu** [comment]
Whether it's really a comment depends on what's inside your macro.
If you run
```
%macro my;
a=3
%mend;
data;
%my *4;
```
The `a` variable will be 12 in your table.
Syntax highlighting won't do macro processing so it's not guaranteed.
