### ISSUE TITLE
Connection IOM 9.4 don't complete (no log)

### ISSUE THREAD

**Issue by duarch** [sassoftware/vscode-sas-extension#1002]
**Describe the bug**
Don't connect. Don't emit any log. Don't time out also. Don't show any nottification as v1.8.0

**Steps to reproduce**
After entering the password the extension start to running the connection, but never complete. 

**Expected behavior**
Connect (I never did it before)

**Screenshots**
![IOMFailure](https://github.com/sassoftware/vscode-sas-extension/assets/42032253/f86097de-e878-48db-b858-7fd343a57e82)

**Environment (please complete the following information):**
Client OS: Windows 10 Enterprise 22H2

Extension version:  v1.9.0 (also tried on v. 1.8.0)
SAS version: 9.04.01M7P08062020

**Additional context**
I usually use SAS Enterprise Guide with the IOM connection.

**Comment by scnwwu** [comment]
duplicate to #964, it will be fixed in v1.10

**Comment by duarch** [comment]
>  it will be fixed in v1.10 

What will be fixed, connection or the log?

**Comment by scnwwu** [comment]
> > it will be fixed in v1.10
> 
> What will be fixed, connection or the log?

Both. Or say, they're single issue.
