### ISSUE TITLE
I18N: Table name in French is split at char 'é' during autocompletion

### ISSUE THREAD

**Issue by scnwwu** [sassoftware/vscode-sas-extension#105]
**Steps to reproduce**
1. Write code
```
data work.vétérinaire;
run;
proc print data=
```
2. Press spacebar so that auto complete popup
3. See incorrect table names are shown: the table name is split at char 'é'.

**Expected behavior**
Table names in French can be auto-completed correctly.

**Environment (please complete the following information):**
Extension version: [v0.1.1]

Ref: NC-15016

**Comment by Zhirong2022** [comment]
The issue has been fixed in the latest topic build.  NLS characters can be recognized as expected.
