### ISSUE TITLE
Enhance SAS Content navigation

### ISSUE THREAD

**Issue by scottdover** [sassoftware/vscode-sas-extension#109]
**Is your feature request related to a problem? Please describe.**
There is a section for future in https://github.com/sassoftware/vscode-sas-extension/issues/56 that this task will resolve

**Describe the solution you'd like**
There are a few things needed for sas content to have more feature parity with SAS drive and vs code:
 - File deletion: Right now, deleting a file permanently deletes it from SAS. In this issue, we'll want to implement the Recycle Bin functionality that is currently part of SAS drive (look for `TODO #109` in the project's code)
 - Drag and drop functionality: Users should be able to drop files from their local machine into SAS content, or move files and folders w/n SAS content
 - Ability to create a favorite: In SAS Drive, a user can favorite a file or folder. We should consider implementing this in the context menu of our sas content pane

**Comment by Becky-Williamson** [comment]
We also need to alphabetize the contents folders in the Explorer pane.

**Comment by boyce-w** [comment]
I'll work on Recycle Bin feature in  #152

**Comment by boyce-w** [comment]
I'll work on the third feature (ability to create favorite) in #283

**Comment by scottdover** [comment]
These changes have been addressed by:
 - https://github.com/sassoftware/vscode-sas-extension/pull/268
 - https://github.com/sassoftware/vscode-sas-extension/issues/283
 - https://github.com/sassoftware/vscode-sas-extension/issues/152
