### ISSUE TITLE
Add Support for Local SAS

### ISSUE THREAD

**Issue by snladg** [sassoftware/vscode-sas-extension#11]
Idea or Feature Request.

The execution environment is currently only available to Viya, which is logical because that is the future.

I was wondering of SAS9 also could be used as execution environment. 
SAS9 is still used by the majority of the SAS customers.
Would that be a big change?

Imagine Code is running on "localhost", where SAS Foundation is also installed. my 2 cents.
Ad

**Comment by shenzj1994** [comment]
+1
Especially considering there is capability already built in other projects like [_saspy_](https://github.com/sassoftware/saspy)

**Comment by jcamato-work** [comment]
+1

**Comment by gro1m** [comment]
@mail2fei Is there a certain timeline for this or is it possible to see the feature backlog? - thanks!
Our organization relies on the Base SAS platform and makes heavy use of SAS Enterprise Guide, which has a rather rudimentary Git integration. Therefore using VS Code for code execution would be really great, as it would also allow to keep SAS and Python code together (regarding data science / machine learning applications).

**Comment by ShuguangSun** [comment]
> +1 Especially considering there is capability already built in other projects like [_saspy_](https://github.com/sassoftware/saspy)

It will help for user with SAS OA/SAS EG as well maybe.

**Comment by gro1m** [comment]
@2TomLi @clangsmith  Is there any timeline for this feature?
We consider to use https://github.com/sasjs/vscode-extension instead, but for this we need to install SASjs server on our Base SAS infrastructure. Therefore it would be really great to have the possibility to use your official VS Code Extension to develop  everything locally in VS Code and run Base SAS code via authentication mechanism. If there is any way to contribute, I'd be happy to help.

@gowerc Is this issue related: https://github.com/sassoftware/vscode-sas-extension/issues/61?

**Comment by 2TomLi** [comment]
We are working on this feature, really appreciate your patience.

**Comment by gowerc** [comment]
@gro1m , yes I believe this is higher related (potentially mine is a duplicate)

**Comment by smorrisj** [comment]
We're going to repurpose this issue to cover implementation of support for targeting a locally installed SAS Installation. #61 is repurposed to target remote via ssh.

**Comment by liuyifan-eric** [comment]
I wonder if the devs have a rough plan/release date for this feature. I am really looking forward to it. Thanks a lot!
