### ISSUE TITLE
Move the profile that is already on the VS Code status bar from the left to the right side of the status bar

### ISSUE THREAD

**Issue by dfxvir** [sassoftware/vscode-sas-extension#113]
**Is your feature request related to a problem? Please describe.**
Consistency problem

**Describe the solution you'd like**
The SAS profile should be moved to the right side of the status bar like it is the case for the other extensions.

**Environment**
SAS Viya and future SAS 9

**Comment by scnwwu** [comment]
According to VS Code's UX guideline
https://code.visualstudio.com/api/ux-guidelines/status-bar

> Items that relate to the entire workspace (status, problems/warnings, sync) go on the left

VS Code's own profile is also on the left.

**Comment by dfxvir** [comment]
Hi Wei
This is weird as typically Python profiles are on the right side
________________________________
De : Wei Wu ***@***.***>
Envoyé : Thursday, February 2, 2023 1:27:34 PM
À : sassoftware/vscode-sas-extension ***@***.***>
Cc : Vincent Rejany ***@***.***>; Author ***@***.***>
Objet : Re: [sassoftware/vscode-sas-extension] Move the profile that is already on the VS Code status bar from the left to the right side of the status bar (Issue #113)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

EXTERNAL

According to VS Code's UX guideline
https://code.visualstudio.com/api/ux-guidelines/status-bar<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2Fapi%2Fux-guidelines%2Fstatus-bar&data=05%7C01%7Cvincent.rejany%40sas.com%7Ce0ab1089e4d847eb307308db0518dcdd%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C638109376569190512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kkkIighCCiOOp5nUD8YKIthqO59R5GU7IHhxN%2Fp0WhA%3D&reserved=0>

Items that relate to the entire workspace (status, problems/warnings, sync) go on the left

VS Code's own profile is also on the left.

**Comment by skyeaussie** [comment]
From reading the guidelines above, our profile should be on the right as we do not play with the entire workspace like VS Code does. For example, we don't interact with some of the main VS code workspace views such as DEBUG COSOLE... etc

**Comment by scnwwu** [comment]
It **can** interact with the entire workspace. It will work with the SAS Explorer pane and the Accounts when we do authentication. SAS log is being displayed in the Output view.
It's also possible to integrate with VS Code's debug view to debug SAS in future. And we can support other languages like Python to submit to Viya in future. And notebooks.
It's also possible to sync Viya preferences with VS Code settings in future.
