### ISSUE TITLE
Extremely long analytic jobs, and quiescent use, time out SSH connections

### ISSUE THREAD

**Issue by chunky** [sassoftware/vscode-sas-extension#1156]
**Describe the bug**
A user reached out to me asking about server timeouts. She will be doing analytic work, then leave her session open while she goes to a meeting or whatever, and when she comes back the connection will have timed out.

**Steps to reproduce**
Configure SSH session, open connection, walk away until you're past whatever your SSH/TCP idle timeout is.

**Expected behavior**
I would like this disconnect to not happen.

**Environment (please complete the following information):**
Client OS: Windows
Extension version: Latest at time of writing
SAS version: 9.4 Linux

**Additional context**
Reading the documentation for ssh2: https://github.com/mscdex/ssh2 , there are two parameters that can be added to the ConnectConfig [around line75, ./client/src/connection/ssh/index.ts ]: keepaliveCountMax and keepaliveInterval.

I suggest:
* keepaliveInterval=30_000; // The keepalives are trivially small, and one every thirty seconds won't even register. It needs to be significantly under the TCP timeout of 90s.
* keepaliveCountMax=2800; // 30s * 2880 = 1 day

**Comment by smorrisj** [comment]
Fixed as part of #1126. Closing.
