### ISSUE TITLE
Column names do not show

### ISSUE THREAD

**Issue by carlosivanr** [sassoftware/vscode-sas-extension#1164]
VS Code is not displaying the column or table names. 

I installed the official SAS extension for VS Code, created a local profile since I have SAS 9.4 windowed environment available to me. I then tried to display several tables from sashelp, but the columns names do not show up. I also tried importing a .csv file and the column names did not show up either.

**Screenshots**
![image](https://github.com/user-attachments/assets/8f060011-72dd-4a21-a3bb-e1505d2397de)
![image](https://github.com/user-attachments/assets/476c7e80-40b4-479a-9890-bc1b8832b5f7)
![image](https://github.com/user-attachments/assets/7f7a2135-40e5-4c57-8613-117f9ba06110)
![image](https://github.com/user-attachments/assets/31b1a6d0-d1e9-4159-9bda-063294dcbb12)

**Environment **
Client OS: Windows 10
Extension version: 1.10.1
SAS version: 9.4

**Comment by scnwwu** [comment]
duplicate to #1114
