### ISSUE TITLE
[SSH Connection] Better results file handling

### ISSUE THREAD

**Issue by ngriffiths21** [sassoftware/vscode-sas-extension#1176]
When using an SSH remote connection with HTML5 results enabled, every SAS submission produces a new .htm file in the home directory on the remote server. In my case, I use the remote server for other activities and want to prevent these files from accumulating (and even if I didn't, it doesn't seem like good practice to fill up the home directory this way).

**Describe the solution you'd like**
It should be possible to configure where the HTML results are stored on the remote server.

**Describe alternatives you've considered**
I tried changing the saspath to a script that first cd's into a custom directory, but this doesn't work because the extension expects the results file in the home directory. The SSH commands used by the extension are not configurable. The only available option appears to be turning off the html5 output, creating a custom "run SAS file" task with preambles and postambles that direct the output to a different location, and loading the results file manually. This is unnecessarily complicated and doesn't make use of the integrated results pane.

**Environment**
SSH remote connection

**Comment by smorrisj** [comment]
For Remote - IOM, we store these ODS HTML5 files in the work directory. This also ensures that they get cleaned up when the session closes. If we were to make the same happen for the Remote - SSH connection method would that work for you?

**Comment by ngriffiths21** [comment]
Yes, that would be a huge improvement because it would be easy to change with command line options.

**Comment by smorrisj** [comment]
> Yes, that would be a huge improvement because it would be easy to change with command line options.
Sounds good. Will try to work this into #1126.

**Comment by smorrisj** [comment]
Fixed in #1126. Part of this PR now by default writes the result files to the work directory. It's now possible to influence the results location by setting the WORK option if desired.
