### ISSUE TITLE
"Run sas file" tasks do not respect selected code

### ISSUE THREAD

**Issue by ngriffiths21** [sassoftware/vscode-sas-extension#1177]
When running the built in "Run sas file" task, or setting up a custom "Run sas file" task with an empty "file" parameter, the task always submits the entire active editor. This contradicts what is in the documentation [here](https://sassoftware.github.io/vscode-sas-extension/Features/runningTask). It is important for custom tasks to respect code selection, otherwise custom preambles/postambles can only be applied to entire SAS files.

**Steps to reproduce the behavior:**

1. Open a new editor window, set SAS language and enter:

%put hello 1;
%put hello 2;

3. Highlight only the second line
4. Open the command palette, choose run task, and "Run sas file." The selection is ignored and both `%put` statements are submitted.

**Environment:**

Client OS: Windows 10
Extension version: v1.10.1
SAS version: 9.4, via SSH remote connection

**Comment by ShermanWang0324** [comment]
Tested the reported issue is fixed, only selected code run by Run Task.
![Screenshot 2024-09-04 170145](https://github.com/user-attachments/assets/b20c887e-b5c7-4691-9256-1ccadfbbdc62)
