### ISSUE TITLE
[format] `run;` not indented in datasets proc

### ISSUE THREAD

**Issue by ShuguangSun** [sassoftware/vscode-sas-extension#1179]
**Describe the bug**
When `Format Doucment`, `run;` is indented, but it should be de-indented and keeps same level as `proc`.

```sas
proc datasets library=work nolist nodetails;
    delete &temptab.;
    run;
```

**Environment (please complete the following information):**
Client OS: Windows 10
Extension version: v1.10.2]

**Comment by scnwwu** [comment]
`PROC DATASETS` supports RUN-group processing. `run` statement does NOT end `PROC DATASETS`. The formatting feature only outdent at procedure ending keyword, in this case, `quit` only.
