### ISSUE TITLE
%include SAS notebooks support on SAS server

### ISSUE THREAD

**Issue by nicrobert** [sassoftware/vscode-sas-extension#1192]
**Is your feature request related to a problem? Please describe.**
I have written a few SAS notebooks that prepare data. The next morning, instead of having to open and run each of them, I want to write a SAS program that run all of them.

**Describe the solution you'd like**
%include "/my/path/dataprep.sasnb" ;

**Describe alternatives you've considered**

**Additional context**

**Environment**
SAS Viya Workbench

**Comment by scnwwu** [comment]
It sounds like not a feature request for this SAS Extension project, but for SAS runtime.

**Comment by snlwih** [comment]
Closing. This is a feature request for SAS runtime.
