### ISSUE TITLE
View SAS Notebooks on github/gitlab

### ISSUE THREAD

**Issue by nicrobert** [sassoftware/vscode-sas-extension#1193]
**Is your feature request related to a problem? Please describe.**
SAS Notebooks can be consumed in VS Code with the VS Code SAS extension. And that's great.
But when pushed to a git repo like gitlab or github, they don't render correctly.

**Describe the solution you'd like**
Display SAS Notebooks in major git platforms like Jupyter notebooks

**Describe alternatives you've considered**

**Additional context**

**Environment**
SAS Viya Workbench

**Comment by scnwwu** [comment]
It has to be supported by Github/Gitlab, out of the scope of this project.

**Comment by snlwih** [comment]
Are we saying that GitHub/GitLab do not have a framework for adding custom viewers, so we couldn't build our own viewer that understands that the .sasnb is actually json and show is using a "notebook viewer"?

**Comment by cjdinger** [comment]
In the early days of Python/Jupyter Notebooks, GitHub did not support rendering them. The solution was to send to another hosted service (nbconvert-related) to read and render. Now GitHub has an integrated viewer, I assume because the format is so popular.

**Comment by scnwwu** [comment]
In case it's helpful, you can easily open a Github repo from VS Code
https://code.visualstudio.com/docs/sourcecontrol/github#_opening-a-repository
Or open a Github Codespace
https://docs.github.com/en/codespaces/overview

**Comment by snlwih** [comment]
From what I understand Github itself is not open source. We can’t contribute unless they provide the ability. Thjerefore closing
