### ISSUE TITLE
Executed Code not shown in Output window

### ISSUE THREAD

**Issue by Lukas67** [sassoftware/vscode-sas-extension#1243]
**Describe the bug**
After opening VSCode the Output window shows the code for the first executions. After a while the code appears for a fraction of a second and disappears. This makes any debugging impossible.

**Steps to reproduce**
Work with SAS in VSCode. You will notice

**Expected behavior**
Flawless work experience with SAS in preferred editor. 
--> no loading time when opening a table
--> no loading time when submitting code statements
--> code shown in output window

**Environment (please complete the following information):**
Client OS: Windows 10 Enterprise
Extension version: v1.11.0
SAS version: SAS 9.4 TS Level 1M7

**Comment by scnwwu** [comment]
Thanks for reporting. I'm working on it.
Please uncheck setting `SAS.log.clearOnExecutionStart` as a temporary workaround.

**Comment by Lukas67** [comment]
Hi Wei Wu,

thank you. That did the trick. 

BR
Lukas
