### ISSUE TITLE
MAC OS X, Certificates, everything...still getting Certificate Authentication Error

### ISSUE THREAD

**Issue by mjbeckernc** [sassoftware/vscode-sas-extension#1257]
So, I’ve done everything in the below for VS Code on my mac:
<img width="869" alt="FirstImage" src="https://github.com/user-attachments/assets/a89a9eb6-68b1-4244-9676-c8127375460c">
 
I can get to the site, the certificate is secure/valid. I’ve pulled it down to my laptop and in the VS Code SAS Settings pointed directly to it. I’ve done the environment variable = 0 on my terminal….and I’m still getting the unable to verify the first certificate.

<img width="871" alt="Image2" src="https://github.com/user-attachments/assets/1ebea36a-5388-4818-8439-1c38c74d9188">

<img width="428" alt="Image3" src="https://github.com/user-attachments/assets/cb61c3fc-861b-4d10-a0da-a04f3c032081">

 
<img width="1089" alt="Image4" src="https://github.com/user-attachments/assets/f4ba8a5e-2bf4-4f20-b8b1-b6241f87faf1">

<img width="1368" alt="Image5" src="https://github.com/user-attachments/assets/55950b45-11c6-4059-9e13-4688221c22d9">

Thank you,
Matt

**Comment by scnwwu** [comment]
Some things to double check:

- Regarding the step 1.4 above, please make sure to select the option with "certificate chain". There're a few options there that may look similar, but other options won't work.
- Regarding the enviornment variable, please make sure it affects your VS Code process. For example a variable set in one terminal may not work for applications started from other processes. I'm not an expert to Mac OS.
- Also worth trying to upgrade your VS Code version to latest if not already.
- Click `Help > Toggle Developer Tools` from the top menu bar to see if any errors from the console.

**Comment by scnwwu** [comment]
No feedback heard. Closing.
