### ISSUE TITLE
Support for Correct UTF-8 Encoding in SAS Notebook Export

### ISSUE THREAD

**Issue by Niram1** [sassoftware/vscode-sas-extension#1280]
**Is your feature request related to a problem? Please describe.**
Yes, when using the current SAS extension to create and export SAS notebooks (.sasnb), certain characters (such as â, é, è, ù, etc.) appear incorrectly in the exported .sas file. These characters get encoded incorrectly due to differences between UTF-8 and another encoding format, resulting in symbols like "Ã©" instead of "é".

**Describe the solution you'd like**
I would like an option to either export the SAS notebook directly in UTF-8 encoding or have a built-in process to convert these characters automatically during the export. This would prevent the need for post-processing corrections on the exported file.

**Describe alternatives you've considered**
I have created a Python script that replaces incorrect characters with the correct ones. However, it would be more efficient and user-friendly if the extension handled this automatically.

**Additional context**
Please see the sample Python code below, which I use to clean up exported files. Integrating a similar solution directly into the SAS notebook export process could solve this issue.

```python
def clean_file(input_file, output_file):
    replacements = {
        "Ã©": "é", "Ã¨": "è", "Ãª": "ê", "Ã": "à", "â€™": "’", "Ã´": "ô",
        "Ã§": "ç", "Ã®": "î", "Ã»": "û", "Ã¨": "è", "Ãª": "ê", "Ã«": "ë",
        "Ã¹": "ù", "Ã€": "À", "Ã‰": "É", "Â": "", "â‚¬": "€", "à§": "ç",
    }

    with open(input_file, 'r', encoding='utf-8') as file:
        text = file.read()
    
    for old, new in replacements.items():
        text = text.replace(old, new)
    
    with open(output_file, 'w', encoding='utf-8') as file:
        file.write(text)
```

I don't know if this would be useful or if I have the skills to do it, but I just wanted to make this suggestion. Thank you very much.

**Comment by scnwwu** [comment]
I didn't reproduce the issue.
I created a new SAS notebook in VS Code with `â, é, è, ù` as a cell content. Then export it to a sas file. The content of the exported sas file is exactly `â, é, è, ù`.
VS Code by default saves files in utf-8 encoding. Have you manually changed the encoding of the sasnb file or changed VS Code builtin setting `files.encoding`?

**Comment by snlwih** [comment]
@Niram1 ,when your system is configured to use UTF-8 for the `files.encoding` everything should work fine. See https://code.visualstudio.com/docs/editor/codebasics#_file-encoding-support.

Have attached the simple SAS notebook I used. Had to provide it as a .zip as .sasnb attachments are not supported as file attachements on comments in GitHub.

[SAS Notebook - Cells contain NLS characters - export test.zip](https://github.com/user-attachments/files/17800628/SAS.Notebook.-.Cells.contain.NLS.characters.-.export.test.zip).

**Comment by scnwwu** [comment]
The Export menu item for SAS Notebook doesn't involve SAS session. SAS session locale or encoding should not impact it.

**Comment by snlwih** [comment]
@Niram1, just like @scnwwu mentioned, the VS code setting applies to the editor panels. Managing the encoding for your SAS session is something that would need to be done in your SAS configuration.

I'm confused now as to what works and what doesn't work. It sounds like you are saying that you have
1. VS Code `files.encoding` set to a non-UTF8 value, which value exactly? 
2. Use a connection (IOM I guess) to a SAS 9.4 M1 server that is configured to run the FR_FR locale?
 ```
  %let encoding = %sysfunc(getoption(encoding));
  %put SAS session encoding: &encoding; 
 ```
3. Create a .sas program (so not a SAS notebook) with SAS code that uses French accented characters
4. Save and close the .sas program
5. Open the .sas program and run it - Does that work as expected?
6. Put the same SAS code in a SAS notebook and run it - Does that work as expected?
7. Save the notebook and close it
8. Open the notebook and run it - Does that work as expected?
9. Export the SAS notebook to a .sas file - Does that work as expected?

Hope this helps.

**Comment by Niram1** [comment]
Hi,

I performed the tests you suggested, and here are my findings:

VS Code Encoding:

I verified the files.encoding setting in VS Code, and it is set to UTF-8.

SAS Session Encoding:

When I open a SAS program, either a SAS notebook (.sasnb) or a standard .sas file, and run the following code:

%let encoding = %sysfunc(getoption(encoding));
%put SAS session encoding: &encoding;
I get the following output:

SAS session encoding: WLATIN1
So, the SAS session encoding is WLATIN1.

Character Display Issue:

Whether I use SAS directly or through VS Code with a SAS session, when I create a .sas program with Latin characters like ùéè in VS Code and run it on SAS, I get characters like Ã©, so the characters are not displayed correctly.
Workaround:

If a solution cannot be found, it's not a major issue since the Python script I wrote works well to correct the characters:

def clean_file(input_file, output_file):
    replacements = {
        "Ã©": "é", "Ã¨": "è", "Ãª": "ê", "Ã": "à", "â€™": "’", "Ã´": "ô",
        "Ã§": "ç", "Ã®": "î", "Ã»": "û", "Ã¨": "è", "Ãª": "ê", "Ã«": "ë",
        "Ã¹": "ù", "Ã€": "À", "Ã‰": "É", "Â": "", "â‚¬": "€", "à§": "ç",
    }

    with open(input_file, 'r', encoding='utf-8') as file:
        text = file.read()
    
    for old, new in replacements.items():
        text = text.replace(old, new)
    
    with open(output_file, 'w', encoding='utf-8') as file:
        file.write(text)
I hope this provides more clarity on the issue.

**Comment by Niram1** [comment]
Attempted to Change SAS Session Encoding to UTF-8:

I tried modifying the SAS configuration file (sasv9.cfg) to set the encoding to UTF-8 by adding -ENCODING UTF-8.

However, when I attempt to start SAS with this change, I encounter the following errors:

ERROR: The ENCODING option value specified is invalid in a SBCS SAS environment.
ERROR: (SASXKRIN): KERNEL RESOURCE INITIALIZATION FAILED.
ERROR: Unable to initialize the SAS kernel.
It appears that my current SAS installation is configured for an SBCS (Single Byte Character Set) environment, which doesn't support UTF-8 encoding.

**Comment by cjdinger** [comment]
The proper way to change the encoding of the SAS session is to use the .../u8/sasv9.cfg, which contains the right mix of options for DBCS and ENCODING. [See this community article for steps](https://communities.sas.com/t5/SAS-Communities-Library/Change-Encoding-using-SAS-Enterprise-Guide-Windowing-Environment/ta-p/597621).

**Comment by Niram1** [comment]
Hello,

The issue was indeed with the file `C:\Program Files\SASHome\SASFoundation\9.4\sasv9.cfg` which contained the line:  
``` 
-config "C:\Program Files\SASHome_foundation\SASFoundation\9.4\nls\fr\sasv9.cfg" 
``` 
This file was using the `WLATIN1` encoding. By redirecting the SAS shortcut to:  
``` 
"C:\Program Files\SASHome_foundation\SASFoundation\9.4\nls\u8\sasv9.cfg"
``` 
and modifying the line in `sasv9.cfg` from:  
``` 
-config "C:\Program Files\SASHome_foundation\SASFoundation\9.4\nls\fr\sasv9.cfg" 
``` 
to:  
``` 
-config "C:\Program Files\SASHome_foundation\SASFoundation\9.4\nls\u8\sasv9.cfg" 
``` 
SAS now opens in UTF-8. However, the interface is now in English. Still, I can now open SAS with special characters without any issues. Sorry for taking your time and thank you very much for your help.
