### ISSUE TITLE
Add libraries content

### ISSUE THREAD

**Issue by scottdover** [sassoftware/vscode-sas-extension#129]
**Is your feature request related to a problem? Please describe.**
As a SAS user, I'd like to use SAS libraries locally so that I'm able to work more effectively.

**Describe the solution you'd like**
 - Libraries should be displayed in a new view similar to SAS content (titled "Libraries")
 - A user should be able to open a library for viewing
 - A user should be able to drag & drop libraries into a text editor for code completion

**Environment**
Viya

**Comment by scottdover** [comment]
Hey @2TomLi @skyeaussie @crlewi. Does the above sound like reasonable acceptance criteria for this feature? Are there other things we're hoping to do in this task? 

Also, @boyce-w @scnwwu, I feel like one of you mentioned an idea of how we may implement table viewing. Do either of you have any thoughts of how we might achieve displaying tables?

Last, @scnwwu, is there an OpenAPI generated api that we should be using for fetching libraries?

**Comment by scnwwu** [comment]
> Last, @scnwwu, is there an OpenAPI generated api that we should be using for fetching libraries?

The libraries API belongs to compute so already there
https://github.com/sassoftware/vscode-sas-extension/blob/main/client/src/connection/rest/api/compute.ts#L7330

**Comment by scnwwu** [comment]
> Also, @boyce-w @scnwwu, I feel like one of you mentioned an idea of how we may implement table viewing. Do either of you have any thoughts of how we might achieve displaying tables?

I believe you're saying @JosephDHenry's demo about
https://github.com/microsoft/vscode-webview-ui-toolkit

**Comment by scottdover** [comment]
Yeah! That's it. Thanks @scnwwu :)

**Comment by scottdover** [comment]
Hey @skyeaussie . From our meeting last week, it looks like I need the follow icons in light/dark variants:

- sasIndicator (this one isn't _really_ from this issue, but I didn't get it put in place for sas content changes)
- library
- workLibrary
- readOnlyLibrary
- sasDataSet
