### ISSUE TITLE
Use VSCode Icons for other file types in SAS Server Files

### ISSUE THREAD

**Issue by engmtcdrm** [sassoftware/vscode-sas-extension#1299]
**Is your feature request related to a problem? Please describe.**
Right now if you are looking at files on the SAS Server filesystem, i.e. Linux it will not provide icons to files that are not `.sas` files. It would be nice if other files types had icons so it was easier to identify what the file is without needing to look at the extension.

**Describe the solution you'd like**
I would like to see icons that are provided from the SAS extension to be pulled from VSCode. VSCode supports a lot of different file extension icons. As well this should support alternative icons sets, but I imagine if setup correctly it wouldn't need to be managed.

**Describe alternatives you've considered**
There is none.

**Additional context**
Below is an example of how non `.sas` files do not have an icon.
![image](https://github.com/user-attachments/assets/faaefff1-df98-4c08-92ef-9d9b34eb4ab7)

**Environment**
SAS version: Viya 4

**Comment by snlwih** [comment]
If more file types are going to be supported with a dedicated icon then this should probably be consistent across the various SAS-owned panels in the SAS Extension.

Here is how files in SAS Content are represented inside the SAS Extension for VS Code:
![image](https://github.com/user-attachments/assets/318214bf-047e-4adf-9867-b26293c726c5)

Here is how the VS Code Folders panel displays these same files:
![image](https://github.com/user-attachments/assets/536fb647-d07a-440c-b75e-1750d22276a7)

Just for reference, here is how those are displayed in the SAS Studio Explorer panel:
![image](https://github.com/user-attachments/assets/d0c74c06-79f3-4baa-a4e5-a06da64180f6)
