### ISSUE TITLE
How to enable syntax highlighting? 

### ISSUE THREAD

**Issue by PavelDvorak** [sassoftware/vscode-sas-extension#13]
Hello
really silly question: 
I installed the extension, but nothing happened. The .sas programs are not recognised, the syntax highlighting doesnt work, no snippets, no autocompletion. I restarted vscode, no effect. What am I doing wrong? 

```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by scnwwu** [comment]
Do you see "SAS" as the language mode on the status bar at bottom right?
Is there any error in the "Log (Extension Host)" output panel?

**Comment by meztez** [comment]
Same issue:
![image](https://user-images.githubusercontent.com/31039074/174611972-f88e0ab0-ba83-4f97-b37c-9b6ddc815976.png)

```
[2022-06-20 09:22:59.797] [exthost] [info] ExtensionService#_doActivateExtension SAS.sas-lsp, startup: false, activationEvent: 'onLanguage:sas'
```

And "SAS" is the detected language mode.

**Comment by scnwwu** [comment]
> I had to use the sas color theme instead of the one I'm currently using.
@meztez SAS color theme is required to see correct syntax highlighting. Other color themes don't have SAS tokens configured.
Autocomplete should work no matter what theme you choose.

**Comment by PavelDvorak** [comment]
thanks for your replies. I changed the language mode manually to SAS, and changed the theme to SAS theme to make the syntax highlighting work. Frankly, the mandatory switch to SAS theme is a killer, especially since other languages' syntaxes are no longer highlighted when using the SAS theme! Is there no way to configure SAS tokens for other themes, as is done for any other language extension? thanks!!

**Comment by scnwwu** [comment]
v0.0.6 published. Now SAS themes provide default colors for non-SAS languages. SAS syntax have basic type colors in non-SAS themes.
