### ISSUE TITLE
Unable to authenticate if you've already logged into SAS Studio

### ISSUE THREAD

**Issue by Becky-Williamson** [sassoftware/vscode-sas-extension#131]
Steps to reproduce:

1.  Set up profiles in VSC to two different servers.  Note which server is displayed at the bottom of the VSC window. (I have profiles for both mwf.seagull-m1.unx.sas.com and tth.seagull-m1.unx.sas.com.  TTH is the one at the bottom of the VSC window.)
2. Close VSC.
3. Start SAS Studio and connect to the server that was NOT displayed at the bottom of the VSC window.  (In my case, MWF)
4. Open VSC and change the profile to the one that you just connected to with SAS Studio by clicking on profile name and selecting the other profile from the selection list.
5. Open the SAS tab and click Sign In
6. Answer Allow to message that says "The extension 'SAS' wants to sign in using SAS.
7. Answer Open to the message that says "Do you want Code to open the external website?"

Expected results:
I'm not sure what should happen here.  I am already logged in so it doesn't make sense to sign in again.

Actual results:
The SAS Logon Manager tab opens in the browser with a message that says "You have signed in" and a Sign out button.  If I go back to VSC and hit escape to cancel the authorization code box, the box closes, but the Sign In button is inactive and I can't get it to come back without closing VSC and reopening it.

**Comment by scnwwu** [comment]
I didn't reproduce it. If I already signed in to SAS Studio, the SASLogon will directly display the authorization code to me.
However, I do think there's an issue to #57. As Becky described, if user cancel the authorization code box, means the user cancelled the Sign in process, the Sign in button should become active again. @scottdover

**Comment by Becky-Williamson** [comment]
I can reproduce this every time.  I'd be happy to demonstrate what I'm seeing if anyone would like to see it.

**Comment by scottdover** [comment]
Hey @Becky-Williamson . I'm wondering if you can reproduce this using the run code button  (in the main branch of code)  instead of the sign in button?

**Comment by Becky-Williamson** [comment]
@scottdover, no, I can't reproduce it using the run code button.  It seems to only happen with the Sign in button.

**Comment by scottdover** [comment]
Hmm. I just checked it on main following the above and _was_ able to reproduce using the run code button and the steps above. 

My hunch is that there are two issues. One is present on main, and has _something_ to do with the recent auth provider changes. The other (the inactive sign in button), I can address in my current set of changes.

**Comment by Becky-Williamson** [comment]
@scottdover, I apologize.  I can reproduce with the run button.  I don't know if I left out a step last time but I just tried it again and I was able to reproduce it.

**Comment by scottdover** [comment]
It also seems like auth isn't working since the new changes have made their way on to the mwf/tth images. At the moment, if you click Authorize Access (see screenshot), things don't redirect and the auth code box isn't dismissed/populated in vscode

![Screenshot 2023-02-21 at 9 38 30 AM](https://user-images.githubusercontent.com/1058265/220393871-98a9fbd9-2e99-4fe7-8117-9d23167214d8.png)

**Comment by Becky-Williamson** [comment]
If I copy the URL into Firefox it does automatically authenticate, both with the run button and the Sign In button.

**Comment by scnwwu** [comment]
The server has been reverted. Not a problem now.
