### ISSUE TITLE
User snippets filename is case sensitive?

### ISSUE THREAD

**Issue by PavelDvorak** [sassoftware/vscode-sas-extension#14]
hello 
at first user snippets were not working (no intellisense). 
My sas programs have an extension ".sas" but the user snippet file was named "SAS.json". After renaming it to "sas.json", the user snippets appear and work as expected. 

Unsure whether it is a bug, but to me this is unexpected behaviour. The filename of the user snippet file should not be case-sensitive.

```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by scnwwu** [comment]
I tried `Manage > Configure User Snippets` and select `sas (SAS)` from the list. It creates "sas.json" file for me.
Are you saying "SAS.json" is automatically created for you by above steps?
Language identifier is case sensitive and should be lowercase. It's by VS Code and not controlled by extension.
https://code.visualstudio.com/docs/languages/identifiers

**Comment by PavelDvorak** [comment]
The "SAS.json" already existed, perhaps created by another extension. It is possible that this SAS extension tried to create "sas.json" but couldnt since on Win the names are case-insensitive. Anyway, as you point out, it is not related to this extension, OK to close. Thanks for your reply!
