### ISSUE TITLE
Support Recycle Bin in the Content Pane

### ISSUE THREAD

**Issue by boyce-w** [sassoftware/vscode-sas-extension#152]
**Is your feature request related to a problem? Please describe.**
This is split from #109 :
File deletion: Right now, deleting a file permanently deletes it from SAS. In this issue, we'll want to implement the Recycle Bin functionality that is currently part of SAS drive (look for TODO #109 in the project's code)

**Describe the solution you'd like**

- In the content navigation pane, add a top level folder Recycle Bin
- Change the 'Delete' action of normal file/folder to move it to the Recycle Bin.
- The Recycle Bin has a context menu item 'Empty Recycle Bin' to delete all the files/folders in the Recycle Bin permanently
- The files/folders in the Recycle has a context menu which has 2 menu items 'Restore' and 'Delete'
- The file in the Recycle Bin is supposed to be opened in read only mode
- The file is supposed to be closed when it's moved to the recycle bin, deleted permanently, or restored from the recycle bin.

**Environment**
SAS Viya

**Comment by crlewi** [comment]
@Zhirong2022 
1. Deleting files or folders from the content tree does not need a confirmation
2. Permanently deleting items from the recycle bin should have confirmation messages.

1. Single item selected warning dialog with title of "Delete" and Delete and Cancel buttons:
Are you sure you want to permanently delete the item "<Item Name>"?

2. Multiple items selected warning dialog with title of "Delete" and Delete and Cancel buttons:
Are you sure you want to permanently delete the selected items?

3.  Empty recycle bin warning dialog with title of "Empty Recycle Bin" and Delete and Cancel buttons:
Are you sure you want to permanently delete all the items? You cannot undo this action.

**Comment by boyce-w** [comment]
fix pushed and close this feature
