### ISSUE TITLE
Running SAS code via vscode tasks.

### ISSUE THREAD

**Issue by JosephDHenry** [sassoftware/vscode-sas-extension#158]
**Is your feature request related to a problem? Please describe.**
Currently the way SAS code is ran is non customizable. You either run the entire file OR run selected code. 
With vscode tasks, execution can be greatly customized.

**Describe the solution you'd like**
The extension should implement a task provider that provides the default "Run current file" and "Run selected text", but allow to create custom SAS execution type tasks.
This would allow the user to customize the preamble and postamble for code execution as well as change ODS preferences and SAS options on a per task basis.

**Comment by dfxvir** [comment]
Could we categorize this one as a feature request.
