### ISSUE TITLE
Errors/Warnings should show up in the editor as they do with other language runtime/compile errors.

### ISSUE THREAD

**Issue by JosephDHenry** [sassoftware/vscode-sas-extension#159]
**Is your feature request related to a problem? Please describe.**
Right now the SAS log shows errors while running, but that information is not reflected in the file that was ran. It would be really nice to see errors and warnings reflected in the editor.

**Describe the solution you'd like**
Errors and warnings should show up in the editor as red or yellow squiggly underline and when you hover over, you should get the error/warning message.

**Comment by QuentinMcMullen** [comment]
Agree.  SAS EG provides similar functionality by having a "log summary" at the top of the output window. After submitting code, you can glance and see the number of notes/warnings/errors.  There needs to be some easy way to know, after running some code, if warnings or errors were written to the log.
