### ISSUE TITLE
Provide an easy way for users to specify the ODS style of the results and automatically use a style that reasonably matches the VS Code theme by default

### ISSUE THREAD

**Issue by clangsmith** [sassoftware/vscode-sas-extension#161]
**Is your feature request related to a problem? Please describe.**
Currently, when SAS code is submitted that creates ODS results, no ODS style is supplied. Therefore, the default ODS style (HTMLEncore) is always used. That default ODS style is light-themed, thus does not fit well with any dark themes. In fact, the contrast is jarring. For example, here is a screenshot of VS Code in the default dark theme, with the default (light-themed) ODS results:
![image](https://user-images.githubusercontent.com/9735352/224436693-9253a62e-00da-4b22-bf07-5558522244b7.png)

**Describe the solution you'd like**
We would like an option that makes it easy for users to change the ODS style used for their results, as well as a reasonably smart default. For example, similar to EG and SAS Studio, the SAS Extension for VS Code should automatically use an ODS style that reasonably matches the VS Code application theme. This means we may want to create some new ODS styles that match certain VS Code themes. At a minimum, we should have (and automatically use) ODS styles that match the two VS Code themes that we ship with our extension, "SAS Light" and "SAS Dark". Currently, the two ODS styles that most closely match those VS Code themes are Illuminate and Ignite, respectively. Would need designers to review to make sure those are the ODS styles we want to use to match, or request new ones be created.

**Describe alternatives you've considered**
Users can workaround by adding code to close the built-in ODS HTML destination, then open their own destination to set the style, but this is cumbersome and most users would have no idea how to do that.

**Additional context**
Again, Studio and EG already do this, so use as a reference.

**Environment**
SAS Viya 4

**Comment by clangsmith** [comment]
See the following animated gif for the built-in VS Code themes with the current default ODS style (none supplied):
![VSCodeThemesWithDefaultODSResultsStyle](https://user-images.githubusercontent.com/9735352/224439313-0e913390-a058-405a-aa54-4cea50549451.gif)
Again, I would not expect us to create new ODS styles to match all of these. Rather, I would expect us to have both a light and dark ODS style that match our "SAS Light" and "SAS Dark" themes that we ship with the our extension. When "automatic" (the default) is selected for the (to-be-created) style option, the light ODS style will be used with any light VS Code themes and the dark ODS style would be used with any dark VS Code themes. If the user doesn't want the automatic style behavior, they should be able to explicitly specify an ODS style to use, which will be used regardless of what the VS Code theme is set to.

**Comment by clangsmith** [comment]
Similarly, it would be nice to automatically select a light or dark high contrast ODS style when a light or dark high contrast theme is used in VS Code.

In VS Code, we are able to tell the color theme kind (Light, Dark, HighContrast, HighContrastLight). So, we really just need reasonable default ODS styles for those categories, even though they will really only match one theme in each category well (ex. SAS Light, SAS Dark, and SAS High Contrast). Here is what I have so far, which works pretty well, except for HighContrastLight, since I'm not aware of any light high contrast ODS themes:

case ColorThemeKind.Light: odsStyle = "Illuminate";
case ColorThemeKind.Dark: odsStyle = "Ignite";
case ColorThemeKind.HighContrast: odsStyle = "HighContrast";
case ColorThemeKind.HighContrastLight: odsStyle = "HighContrast";

So, the question goes to @crlewi and @skyeaussie (and the design team)... are these the SAS styles you want us to use with these themes? Or should new themes be created?

I'll link a PR with these changes shortly, so you can see what it currently looks like with this logic.

**Comment by clangsmith** [comment]
Also, I assume we would add the new ODS style option underneath the existing "Enable/disable ODS HTML5 output" checkbox (since they are related) in the extension settings. The option could be a checkbox (unchecked by default) with text similar to "Use style for results:" followed by a combobox with ODS style names. When unchecked, the "automatic" style behavior would be in effect. Or, rather than a checkbox and combobox, you could have just a label with text similar to "Use style for results:" and a combobox with the style names and "(Auto)" at the top and selected by default,

**Comment by skyeaussie** [comment]
@clangsmith Is this what you were thinking?
<img width="360" alt="image" src="https://user-images.githubusercontent.com/25531424/225732358-60476507-97e8-4834-962e-450f3ca32846.png">
As far as this question "are these the SAS styles you want us to use with these themes? Or should new themes be created?" I believe that the visual design group is not creating new themes but updating HTMLBlue (light) and HTMLEncore (dark) (i think).

**Comment by Cleester4** [comment]
If you use "Default" to mean the ODS destination default, you should probably wrap it with parentheses (i.e. (Default)). That's because there actually is a style in ODS called "Default". As for changing HTMLBlue and HTMLEncore, that could have a lot of implications for users in the field, as they are the defaults for HTML and HTML5, respectively.

Over time, we have created other "VA-based" styles in ODS, including:
- Aqua
- Marine
- Umstead
- Illuminate
- Ignite
- HighContrast
In addition to the regular style definitions, there are also versions of those styles tuned for Word, Excel, and Powerpoint output. It would seem better to expand this collection instead of changing established default styles, unless there just bugs that need to be fixed.

**Comment by clangsmith** [comment]
@skyeaussie yes, that is what I was thinking. I agree with @Cleester4 that "default" should also be wrapped in parens. I also debated whether "(auto)" and "(default)" were too similar and or confusing that "(default)" is not the default for that option ("(auto)" will be the default). Thus, I was considering whether "(server default)" would better reflect -- not explicitly specifying a style in code, thus the default ODS style on the server will be used. Using "(none)" doesn't seem appropriate, since a style is still used even if not specified. So, I am thinking it is between "(default)" and "(server default)". I am leaning toward the latter unless someone else feels otherwise..

**Comment by crlewi** [comment]
@clangsmith "(server default)" should work. I updated it in the VS Code spec. Thanks!

**Comment by clangsmith** [comment]
@Cleester4, @skyeaussie, @crlewi, what specific ODS styles should we include in the extension's UI option? I am planning to include Illuminate, Ignite, and HighContrast at a minimum. I'm not sure we want to hard-code all the styles defined on the server (list below for example), since that will make it look like we tried to include them all and will likely quickly get out of date. (Not planning to try to dynamically populate the list, since that would require a connection to the server and could vary by server.) I was thinking we'd hard code some number of the more popular styles and then for any others that a user may want to use, they can still explicitly specify it in the settings.json file even if it isn't exposed in the option UI.

I ran the SAS code "proc sql; select * from sashelp.vstyle; quit;" on latest Viya 4 (2023.09) using SAS Studio and here are the styles (60 total) that were defined:

Aqua, Daisy, Default, Dove, EGDefault, Excel, ExcelAqua, ExcelHighContrast, ExcelIgnite, ExcelIlluminate, ExcelMarine, ExcelMidnight, ExcelOpal, ExcelUmstead, HighContrast, HighContrastLarge, HTMLBlue, HTMLEncore, Ignite, Illuminate, Journal, Journal2, Journal3, Listing, Marine, Midnight, Moonflower, Opal, Pearl, PearlJ, Plateau, PowerPointAqua, PowerPointDark, PowerPointHighContrast, PowerPointIgnite, PowerPointIlluminate, PowerPointLight, PowerPointMarine, PowerPointMidnight, PowerPointOpal, PowerPointUmstead, Printer, Raven, Rtf, Sapphire, Snow, Statistical, Umstead, vaDark, vaHighContrast, vaLight, Word, WordAqua, WordHighContrast, WordIgnite, WordIlluminate, WordMarine, WordMidnight, WordOpal, WordUmstead

**Comment by clangsmith** [comment]
Attaching the ODS styles defined by default (OOTB) in Viya 4, Viya 3.5, and SAS 9.4M8. Another option would be to include all the styles that exist on each platform. Or, we could still include Viya 4 only styles as well and just append something like "(Viya 4 only)" after the style name. Still trying to decide which styles it makes the most sense to include in the option UI (combobox).
[odsStylesBySASPlatform.xlsx](https://github.com/sassoftware/vscode-sas-extension/files/12442860/odsStylesBySASPlatform.xlsx)

**Comment by clangsmith** [comment]
Going to go with the following styles recommended by @Cleester4 for HTML5:
Aqua, Daisy, Dove, HighContrast, HighContrastLarge, HTMLBlue, HTMLEncore, Ignite, Illuminate, Journal, Journal2, Journal3, Marine, Midnight, Moonflower, Opal, Pearl, Sapphire

Of those, these styles are defined on Viya 4 only (not in Viya 3.5 or V9):
Aqua, Marine, Midnight, Opal

The first list above are all the styles defined on Viya 4 by default, except for these (which are ideally for other ODS destinations or otherwise don't fit HTML5 well):
Default, EGDefault, Excel, ExcelAqua, ExcelHighContrast, ExcelIgnite, ExcelIlluminate, ExcelMarine, ExcelMidnight, ExcelOpal, ExcelUmstead, Listing, PearlJ, Plateau, PowerPointAqua, PowerPointDark, PowerPointHighContrast, PowerPointIgnite, PowerPointIlluminate, PowerPointLight, PowerPointMarine, PowerPointMidnight, PowerPointOpal, PowerPointUmstead, Printer, Raven, Rtf

As noted previously, any styles (built-in or user-defined) can still be used by explicitly specifying in the settings.json file. For example...
"SAS.results.html.style": "EGDefault"

For now, I'm not going to append "(Viya 4 only)" to the styles that are only defined in Viya 4, and not going to worry about the warning that appears when you specify a value in the settings.json that does not correspond with an enum, since it is just a warning and still works.
