### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by chulgyu100** [sassoftware/vscode-sas-extension#17]
When I submit sas code, got the below error.
{"service":"compute","detail":{"status":0,"statusText":"Invalid character in header content [\"Authorization\"]","detail":" ","error":true}}

What's wrong with me?

**Comment by chulgyu100** [comment]
I did set the below in the extension settings page.
context: SAS Job Execution compute context
Host: xxxx.xxx.sas.com <-- Viya 3.5 host
Token File : entered the full path of token file. ex) c:\temp\token.txt

**Comment by scnwwu** [comment]
Does your token file contain line breaks or non-ANSI encoding? The extension will simply take the whole content as the bearer token. It may introduce invalid character to request header.

**Comment by chulgyu100** [comment]
token file contains token info that generated by Postman api call.
Perhaps, that is UTF-8 format.
I changed to ANSI/ASCII format and tried to connect. But, new error occured.

{"service":"compute","detail":{"status":0,"statusText":"connect ECONNREFUSED 127.0.0.1:80","detail":" ","error":true}}

**Comment by scnwwu** [comment]
ECONNREFUSED usually means bad protocol. Did you specify the correct protocol (http:// or https://) for your Viya URL?

**Comment by chulgyu100** [comment]
Great! 
I entered the host name only. There is no the protocol.
I think that the readme file of github and setting section of extension is change to have the example of host field.
Thanks,

**Comment by jefurbee** [comment]
I've forked the repo and am working on some proposed changes to the README. I can certainly include configuration hints and examples. I hope to have a PR ready early next week.
