### ISSUE TITLE
Add a way to specify SAS Options for Session

### ISSUE THREAD

**Issue by JosephDHenry** [sassoftware/vscode-sas-extension#184]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to specify SAS options for a session startup. All connections are made with default SAS options.

**Describe the solution you'd like**
The connection profile should have a section for SAS options that would be specified on Session startup. This would most likely be a JSON map like:

`{
"options": {
   "MEMSIZE": "0"
  }
}`

**Comment by smorrisj** [comment]
@JosephDHenry  would they need to be defined as key/value pair objects? Theoretically could also do:

`{"options": ["-NONEWS", "-MEMSIZE 0"]}`

I suppose its a question of whether or not we want to be able to interact with these in a deeper way than just passing them around as switches.

**Comment by JosephDHenry** [comment]
Yeah, so the array of options like you mentioned works well because that is the format that the SAS compute API requires.
