### ISSUE TITLE
Libraries created via code are not displayed in the Libraries pane

### ISSUE THREAD

**Issue by Becky-Williamson** [sassoftware/vscode-sas-extension#192]
Steps to reproduce:

1. Submit the following code to create a table in the WORK library:  data test; set sashelp.class; run;
2. Submit the following code to assign CAS libraries and create CAS libraries: 
          cas; caslib _ALL_ assign;
          data casuser.cascars; set sashelp.cars; run;
          proc casutil; load data=SASHELP.BASEBALL outcaslib="CASUSER" casout="CASBALL";run;

Expected results:
A table called test should be available in the WORK library
All CAS tables available on the server should be assigned and visible. 
A table called cascars should be available in CASUSER library
A table called casball should be available in CASUSER library

Actual results:
None of the libraries or tables assigned or created by the above code are visible in the Libraries tree, even after refreshing the tree.

**Comment by scottdover** [comment]
> That said, one thing I've noticed is that the refresh is triggered before the code is actually finished...which seems to be an issue

This was exactly it. `run` is an asynchronous operation, but I wasn't waiting for it to finish before I refreshed library information

**Comment by Becky-Williamson** [comment]
What server were you connected to?  I was connected to https://tth.seagull-m1.unx.sas.com and I am not seeing that behavior.  I just retried it and they are still not showing up.

**Comment by Becky-Williamson** [comment]
Ok, so it must be something with the  https://tth.seagull-m1.unx.sas.com/ server.  When I connect to https://vmlmwf.ingress-nginx.vmlmwf-m1.quest.sashq-d.openstack.sas.com/ I am seeing the tables in the Libraries pane.

**Comment by Becky-Williamson** [comment]
I am unable to reproduce this today so I'm going to close this issue.

**Comment by Becky-Williamson** [comment]
No longer able to reproduce.
