### ISSUE TITLE
If you are not an authorized user under the End User Agreement, you may not download the Code.

### ISSUE THREAD

**Issue by allanbowe** [sassoftware/vscode-sas-extension#2]
Firstly - congrats and thankyou for building this extension!  It has immense value for SAS Developers who prefer VS Code.

Just one small (actually, massive) issue.  The licence is extremely restrictive.  As it stands, per the terms of use, I myself am not allowed to download it! 

Beyond licencing issues from usage, there is also no scope for third party developers to build on the great work that has been done (eg to embed the language server in other IDEs). 

Any plans for more permissive licensing?

**Comment by mail2fei** [comment]
Has conveyed your message to the relevant department in SAS. Thanks for your feedback.

**Comment by allanbowe** [comment]
Thanks Chris.

I guess my main question / concern is this.  We've been waiting a long time to see a Language Server for SAS to enable a rich developer experience whenever surfacing a code editor with SAS flavouring.

The work done here by @mail2fei and team is outstanding and we'd like for it to be showcased in third party applications.

Specifically, this can make a massive difference to the user experience where an application requires SAS Code entry - and there are many examples.  Just yesterday I was speaking with a customer who had two web applications that required end users to type / enter SAS code.

We'd also love to make use of the Language Server in open source, SASjs products.

How to proceed?

**Comment by cjdinger** [comment]
I believe that the license doesn't allow for that use case, but I will verify and post back if that's not the case. With this license in place, we are able to release this extension for direct use by SAS end users (including those learning/student cases I mentioned). I realize that some might like to take it further, but that's all we can offer for now.
