### ISSUE TITLE
Change the icon of Folders to have an unified theme 

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#214]
**Is your feature request related to a problem? Please describe.**
Suggest to change the icon for 'My Favorites ', 'May Folder', 'SAS Content' and 'Recycle Bin' to be able to have an unified look an feel with items under Libraries.

Please refer icons in SASDirve
![image](https://user-images.githubusercontent.com/121005702/230583710-ea74e27e-5e06-4593-9be9-524ed43432b9.png)

**Environment**
SAS version

**Comment by boyce-w** [comment]
Hi @skyeaussie , I noticed that the sas program file and library icon has a different color from SAS Studio and SAS Drive, do we also need different icons for these delegate folders?

**Comment by skyeaussie** [comment]
@boyce-w These are the official colors for the icons. I think they are correct in VS Code. 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/25531424/236007072-b2a2a39d-9eba-4b14-bf54-2d32d4aa0dd1.png">

**Comment by skyeaussie** [comment]
@boyce-w @Zhirong2022  We (UX) will get the 'delegate folder' icons (SAS Content, Folder (general), My Favorites, & Recycle Bin) requested. Will let you know when they are available.

**Comment by skyeaussie** [comment]
@boyce-w  Icons are now available.
