### ISSUE TITLE
Windows connectivity issues

### ISSUE THREAD

**Issue by scottdover** [sassoftware/vscode-sas-extension#215]
**Describe the bug**
In doing some testing for the 0.1.3 release, there were a few issues discovered around connectivity that were only present on a windows machine. 

**Steps to reproduce**
Scenario 1 (clicking the "Sign in" button with no profile)
 - Click Sign in from the SAS pane
 - Enter connection name
 - Select SAS Viya
 - Enter a Viya URL
 - Accept defaults
 - Click Allow (allowing authentication)
 - Click Open (to open sas url)
 - Sign in
 - Copy code
 - Paste in VSCE
 - At this point, the user is asked to sign in again, and SAS content/libraries are not loaded

 Scenario 2 (choosing to run SAS code with no profile)
 - Create a new SAS program and click running man icon
 - Enter connection name
 - Select SAS Viya
 - Enter a Viya URL
 - Accept defaults
 - _at this point, we should be prompted to sign in. This isn't happening_
 - Click running man again
 - Click Allow (allowing authentication)
 - Click Open (to open sas url)
 - Copy code
 - Paste in VSCE
 - _at this point, VSCE connects to SAS and program runs. Additionally, when the SAS pane is clicked, the user is asked to sign in again. However, they should already be signed in since they ran SAS code_

**Expected behavior**

**Environment (please complete the following information):**
Client OS: Windows
Extension version: `main` (https://github.com/sassoftware/vscode-sas-extension/commit/ff2acf77720189f7d41cde5adb565efad67a0690)
SAS version: Viya mwf/tth builds

**Additional context**
- Joseph Henry found a SAS certificate issue that could be causing these problems. However, when using `"http.proxyStrictSSL": false` in user settings, things remain unresolved.

**Comment by scottdover** [comment]
It looks like there are oddities with how credential storing works on Windows. See the following:
 - https://github.com/microsoft/vscode/issues/179202
 - https://github.com/microsoft/vscode/issues/165115

At the moment, this issue only comes up when a user has multiple profiles and is using Windows. A workaround is to clear out vscode's cache using the following script:
```sh
cmdkey /list | Select-String -Pattern "LegacyGeneric:target=(vscode.+)" | ForEach-Object { cmdkey.exe /delete $_.Matches.Groups[1].Value }
```

@scnwwu, do you mind adding a comment or editing this one providing more detail on how this can be resolved using Windows Credential Manager

**Comment by scnwwu** [comment]
To clear the credentials for SAS extension only, open `Control Panel\All Control Panel Items\Credential Manager`, click `Windows Credentials`, find items start with `vscodesas`, click `Remove`.

**Comment by scnwwu** [comment]
The dependent VS Code issue has been fixed. It should no longer be a problem in latest VS Code.
