### ISSUE TITLE
honor Caps Lock status when autocompleting

### ISSUE THREAD

**Issue by KDeser** [sassoftware/vscode-sas-extension#22]
I'm oldschool and like to write SAS code in ALL CAPS. 

Can the autocomplete abide by this? If the user has Caps Lock on, autocompleted code should be entered in ALL CAPS.

**Comment by mail2fei** [comment]
We will evaluate the feature to see the feasibility and cost in the extension.

**Comment by scnwwu** [comment]
An update: VS Code said they won't do in client side.
https://github.com/microsoft/vscode/issues/156125
