### ISSUE TITLE
Folder children in Explorer pane not displayed in a logical, expected, or consistent order

### ISSUE THREAD

**Issue by clangsmith** [sassoftware/vscode-sas-extension#225]
**Describe the bug**
In the SAS' Explorer pane, child folders and files are not displayed in any clear order (not alphabetical order) and not consistent with how they are ordered in SAS Studio. (Anecdotally, it looks like they are in order of creation.) In SAS Studio, the folders are displayed first in alphabetical order, then the files are displayed, again in alphabetical order. (see screenshot below)

**Steps to reproduce**

1. Open the Explorer pane in SAS Studio and the Explorer pane in VS Code (connected to the same environment).
2. Expand the Public folder.
3. If there is not much content already in there, create several folders and files.
4. Notice that the folders and files are not displayed in alphabetical order in VS Code and are not consistent with the order they are displayed in SAS Studio.

**Expected behavior**
The folders and files should be ordered consistent with the way they are in SAS Studio (folders first, in alphabetical order, then files, also in alphabetical order).

**Screenshots**
![image](https://user-images.githubusercontent.com/9735352/231585419-33fbaed3-4166-4bfa-9943-079f96d19c02.png)

**Environment (please complete the following information):**
Client OS: Windows 10
Extension version: v0.1.3
SAS version: Viya 2023.04

**Comment by boyce-w** [comment]
Working on it

**Comment by Becky-Williamson** [comment]
Should alphabetization be grouped by uppper/lower case?  I'm seeing it alphabetize upper case letters first and lower case letters after.  
![image](https://user-images.githubusercontent.com/72519703/231847518-49d1a07f-f872-4e43-9ffa-2dba08de8d1a.png)

**Comment by boyce-w** [comment]
> Should alphabetization be grouped by uppper/lower case? I'm seeing it alphabetize upper case letters first and lower case letters after. 

No problem. This has been fixed in the latest commit.
