### ISSUE TITLE
Cannot run SAS code in VSCode with extension if project is loaded in a WSL Window in VSCode

### ISSUE THREAD

**Issue by michelledelaurentis** [sassoftware/vscode-sas-extension#242]
**Describe the bug**
I am running on a VMW(windows) with Ubuntu 2 20.04 I just installed the SAS Code extension for VSCode
If I open my project in a WSL window, as suggested by VSCode, I cannot run .sas files. I am not prompted to open VIYA, I see Connecting to SAS ... and eventually the window disappears, I'm assuming it times out. 

**Steps to reproduce**
I would be happy to demo the issue for you.
1. get a windows vm
2. install WSL2 20.04
3. Open a .sas file in an Ubuntu window 
![image](https://user-images.githubusercontent.com/131207855/232905714-f35ec8a8-97ed-4ae4-b3a2-1a2b7ce9926b.png)
4. Click the 'running man' to run the .sas code
5. You will not be prompted for the auth code and a window at the bottom of VSCode appears 'Connectin to SAS...' which eventually disappears.

**Expected behavior**
I would expect that I am prompted to open VIYA, where I log in and get the auth code to use in VSCode

**Screenshots**

**Environment (please complete the following information):**
Client OS: Windows 10 version 21H2 VM with WSL2 Ubuntu 20.04
Extension version: see above
SAS version: Viya 2023.03

**Additional context**
In this screenshot
![image](https://user-images.githubusercontent.com/131207855/232907005-6ac02d3e-bd35-4591-896d-ad23ee6bfee9.png)
when I open the project in blue I am never prompted to open VIYA. When I open the project highlighted in yellow everything works as expected.

**Comment by michelledelaurentis** [comment]
Please replace the last screenshot with the one below
![image](https://user-images.githubusercontent.com/131207855/232907679-bce49212-20c9-476f-9bfa-bdcaf4690220.png)

**Comment by scnwwu** [comment]
It works on my WSL2. Have you installed the extension into your WSL2? The extension needs to be run in WSL2.

**Comment by michelledelaurentis** [comment]
I assume then that the extension being enabled on WSL is not the same
![image](https://user-images.githubusercontent.com/131207855/233088455-713decc7-3c95-4248-8016-ccb1bfa57da9.png)
And I do see it under the list of WSL installed extensions
![image](https://user-images.githubusercontent.com/131207855/233088869-ab895203-d9fe-4301-bb29-8f26e84d2fd4.png)
but do not find the settings.json file in Ubuntu
![image](https://user-images.githubusercontent.com/131207855/233089677-6b1e497e-095f-438d-b6dc-00d1d59ee16c.png)
What am I missing?
Thanks for your help!

**Comment by scnwwu** [comment]
VS Code has a hierarchy of settings. If it cannot find a profile it should prompt for a profile. So settings.json looks not a problem now.
Timeout sounds not related to the extension. Are you able to make http(s) request to your server in your WSL terminal?
