### ISSUE TITLE
Remediate SAST vulnerabilities reported by Snyk scan

### ISSUE THREAD

**Issue by damack70** [sassoftware/vscode-sas-extension#248]
Running the Snyk CLI (snyk code test -d .) on the vscode-sas-extension project showed 6 vulnerabilities.  After discussion with development,  we agreed that two are false positives and can be ignored.  
I'm entering this bug to get the other 4 vulnerabilities remediated.  
From the scan:
 ✗ [Medium] SQL Injection
   Path: client/src/components/ContentNavigator/ContentModel.ts, line 120
   Info: Unsanitized input from the database flows into get, where it is used in an SQL query. This may result in an SQL Injection vulnerability.

 ✗ [Medium] SQL Injection
   Path: client/src/components/ContentNavigator/ContentModel.ts, line 312
   Info: Unsanitized input from the database flows into get, where it is used in an SQL query. This may result in an SQL Injection vulnerability.

 ✗ [Medium] SQL Injection
   Path: client/src/components/ContentNavigator/ContentModel.ts, line 317
   Info: Unsanitized input from the database flows into get, where it is used in an SQL query. This may result in an SQL Injection vulnerability.

 ✗ [Medium] SQL Injection
   Path: client/src/components/ContentNavigator/ContentModel.ts, line 318
   Info: Unsanitized input from the database flows into get, where it is used in an SQL query. This may result in an SQL Injection vulnerability.

**Comment by boyce-w** [comment]
I think all of them are false positive as well. The query uri in ContentModel are concatenated with the 'link' attribute of the item which is fetched from the service and some hardcoded query parameters. No user input.

So, I don't think there would be security risk.
