### ISSUE TITLE
Proc summary - incomplete syntax highlighting

### ISSUE THREAD

**Issue by PavelDvorak** [sassoftware/vscode-sas-extension#249]
**Describe the bug**
PROC MEANS and PROC SUMMARY are almost the same, but the syntax highlighting in this extension only works well for PROC MEANS.

**Steps to reproduce**
paste this code in vscode, check highlighting.
```
proc summary nway data = CDDP5_DD completetypes;
	class Entity_ID;
    class semester;
    class geo;
    class field_code_short ;
    class Metric;
	var value_euro;
	
	output out = CDDP5_DD_1  (DROP = _TYPE_ _FREQ_)  sum = ;
run;

proc means nway data = CDDP5_DD completetypes;
	class Entity_ID;
    class semester;
    class geo;
    class field_code_short ;
    class Metric;
	var value_euro;
	
	output out = CDDP5_DD_1  (DROP = _TYPE_ _FREQ_)  sum = ;
run;
```

**Expected behavior**
Same syntax highlighting for PROC MEANS and PROC SUMMARY. 

**Screenshots**

**Environment (please complete the following information):**
Client OS:  Windows 10
Extension version: v0.1.8
SAS version: 9.4M7

**Comment by scnwwu** [comment]
Should be fixed in v0.1.5
