### ISSUE TITLE
No error? No results either

### ISSUE THREAD

**Issue by meingraham** [sassoftware/vscode-sas-extension#25]
I have installed the extension and configured it to point to my Viya 4 endpoint (https protocol) and authenticate via an access token as per the link in the FAQ.

I have added the Viya CA certificate to my trust store.

When I run

```sas
data public.cars2;
set public.cars;
mpg=(mpg_highway + mpg_city) / 2;
run;
```

I get an error (I think), but there is no message. The vscode popup has the red "error" icon followed by `{}` and `Source: SAS (Extension)`. That's all.

Where can I look for more information? Which pod(s) should be responding? I'd like to take a look through the logs to see if there are any clues.

Cheers!

**Comment by scnwwu** [comment]
Would you restart VS Code and try again to see what's the first error message?

**Comment by meingraham** [comment]
Fresh VSCode start:

`{"service":"compute","detail":{"status":0,"statusText":"unable to verify the first certificate","detail":" ","error":true}}`

I confirmed the the Viya CA certificate I retrieved

```bash
kubectl -n viya get secret sas-viya-ca-certificate-secret -o go-template='{{(index .data "ca.crt")}}' | base64 -d > ./viya_ca_certificate.crt
```
is in my Ubunty Linux cert trust store.

I then follow the recommended `Close Current Session` from the FAQ

I re-submit the code. I briefly see a `Connecting to SAS Session`. Then I see the "empty" error.

**Comment by meingraham** [comment]
When I obtained the access token, this is the `curl` command I used in my script.

`INGRESS_URL` is my Viya endpoint (https)
`client_id` and `client_secret` are the variables I set in my script

Do I have the right scopes? I wasn't sure if `group1` applied to this VSCode extension client. I tried it with and without (I deregistered the client and re-registered with different scopes). What about the grant types? Are they right for this client? `redirect_uri`? I'm asking because the authentication article linked in the extension setup instructions seems generic and not necessarily specifically for the VSCode extension.

```bash
curl -k -X POST "$INGRESS_URL/SASLogon/oauth/clients" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $IDTOKEN" \
    -d '{
      "client_id": "'${client_id}'", 
      "client_secret": "'${client_secret}'",
      "scope": ["openid"],
      "authorized_grant_types": ["authorization_code","refresh_token"],
      "redirect_uri": "urn:ietf:wg:oauth:2.0:oob"
    }'
```

**Comment by meingraham** [comment]
An update for anybody else coming across a similar situation. Wei provided a workaround which was able to make remote SAS code execution work from my Linux VM. This has not resolved the issue in submitting SAS code remotely from my Windows workstation.

Certificate issue workaround:  
- Define an environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0`. This environment variable will bypass the certificate check.  
    Linux - edit `~/.bashrc` to append this definition  
    Windows - define the variable as a system variable  
- Exit VSCode  
- Ensure that there are no VSCode processes running  
  Linux - `ps -aux | grep vscode-server`  
  Windows - `tasklist /NH | findstr /I Code.exe`  

Try running SAS from within VSCode again  

The main push for me was to be able to use remote submitting from my Linux environment. So, for now, I'm moving forward with the workaround above.  

In the future, time permitting, I want to investigate further some additional suggestions.  

- There’s a [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#node_extra_ca_certsfile) environment variable that can specify extra certificate files so that you don’t need to bypass TLS.

- There’s an extension [win-ca](https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca) that indicates that it can make certificates available to VS Code extensions. But isn't there a setting already in VS Code that let's it load CA certificates from the OS?
