### ISSUE TITLE
Add support for PROC SQL code highlighting.

### ISSUE THREAD

**Issue by postcanonical** [sassoftware/vscode-sas-extension#26]
PROC SQL code is highlighted only at first statement like `create table` or `select`, but `from`, `where` etc. won't highlight. Now it's working like SAS code, so it will highlight statement after semi-column, but SQL code uses semi-column to differentiate queries. Furthermore, snippet for PROC SQL pasting wrong code with semi-columns before `from` and `where`.

Like this:
```{sas}
proc sql;
   select ;
   from ;
   where ;
run;
```

**Comment by scnwwu** [comment]
Thank you for reporting this. The built-in SQL snippet has been corrected in v0.1.0
We need some further evaluation for approaches to handle the embedded languages.

**Comment by FattyNess** [comment]
Thank you for the correction. It would be nice to use `quit;` rather then `run;` in `proc sql`. Waiting for sql code highlighting in future updates.

**Comment by scnwwu** [comment]
Ah, pushed a fix for the `quit`. It will show up on next release. Thank you again.

**Comment by Enzhihpp** [comment]
NC-14157 also mentioned the similar issue:
-------------------------------------------
Release: 20221116.1668633295625
Client OS: 64bit Win 10
Browser: Firefox
Server: https://daily.pgc.unx.sas.com/
Steps:
1. Make sure you have switched to Monaco Editor by feature flag.
2. Launch Excel and log in AMO add-in 
3. Go to Programs tab, copy and paste following code to editor:
proc sql;
create table sasstudio_next_cov as
select *
from work.sasstudio_next
where test_class_nm eq 'Coverage' and test_nm not eq 'practice_sas_studio_app'
group by test_nm, test_level_path_txt
having test_run_start_dttm = max(test_run_start_dttm)
order by test_nm, test_level_path_txt, metric_nm;
quit;
Actual Results:
As attached screen 'Syntax highlighting issue.jpg', Syntax Highlighting doesn't work well for Proc sql code in AMO Monaco Editor.
Expected Results:
Syntax Highlighting works well for Proc sql code in AMO Monaco Editor.
