### ISSUE TITLE
After login, Request failed with status code 405

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/vscode-sas-extension#265]
**Describe the bug**

**Steps to reproduce**

Login from left panel with an oauth client

**Expected behavior**
See SAS library

**Screenshots**

**Environment (please complete the following information):**
Client OS: macos
Extension version: 0.1.13
SAS version: Viya 3.5

**Additional context**
After login is successful and I paste the authorization code, I see the errors `Cannot read properties of undefined (reading 'split')` and `Cannot read properties of undefined (reading '0')`.
If I try again with login already done, the error is `Request failed with status code 405`

**Comment by scnwwu** [comment]
Should be fixed in v0.1.5
