### ISSUE TITLE
SAS OnDemand for Academics connection profile option

### ISSUE THREAD

**Issue by jnvickery** [sassoftware/vscode-sas-extension#269]
It's possible to connect to ODA via [saspy](https://github.com/sassoftware/saspy) (https://support.sas.com/ondemand/saspy.html).

Would it be possible to add an ODA connection profile for the vscode extension?

**Comment by scnwwu** [comment]
Please refer to
https://communities.sas.com/t5/SAS-Communities-Library/How-to-use-VS-Code-with-SAS-OnDemand-for-Academics/ta-p/914928
