### ISSUE TITLE
SAS Viya 3.5 usage?

### ISSUE THREAD

**Issue by jan-ehlers** [sassoftware/vscode-sas-extension#27]
Is this extension supported for Viya 3.5?

**Comment by scnwwu** [comment]
I did see someone connected to Viya 3.5 successfully. Any specific issue are you seeing?

**Comment by jan-ehlers** [comment]
Hi Wei

I did not have any specific issues, but wanted to mentioned the good news of this extension to a large audience yesterday, where many are still using Viya 3.5, and I did not find any documented system requirements anywhere. Therefore I suggest you add system requirements to the documentation. Eg. Viya 3.5 Full deployment and Viya 2021.x and newer is supported, except Analytics Pro.

Regards, Jan

**Comment by scottdover** [comment]
Closing this one due to a lack of activity
