### ISSUE TITLE
Not supported on Linux RedHat ?

### ISSUE THREAD

**Issue by mbertol4** [sassoftware/vscode-sas-extension#275]
Hi, is the extension supported for VSCode on Linux RedHat ?  We have not been able to install on RedHat Linux, silent failure observed.

Thanks

**Comment by scnwwu** [comment]
Can you install other extensions well?
What RedHat version are you using?
Are you using VS Code directly on RedHat or remote connect to it?
Would you open `Help > Toggle Developer Tools` in VS Code and see if any error?

**Comment by mbertol4** [comment]
Hi, yes we can have other extensions installed without issue.
It's RedHat version 7  
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
but we have the same also with version 8

VS Code is executed 
Code - OSS
code-server: v4.4.0
Code: 1.66.2

**Comment by scnwwu** [comment]
hi, would you mind try upgrading your VS Code version？

________________________________

**Comment by Zhirong2022** [comment]
I can install SAS Extension successfully with VS Code1.78.0.  Everything goes smoothly without failure.

**Comment by scnwwu** [comment]
No additional comment for a while. Closing. Please comment if any problem with latest version.
