### ISSUE TITLE
Add to Favorites / Remove from Favorites action in Content Navigation

### ISSUE THREAD

**Issue by boyce-w** [sassoftware/vscode-sas-extension#283]
**Is your feature request related to a problem? Please describe.**
This is split from #109 :
Provide ability to add a reference of an item to My Favorites folder and ability to remove the reference from My Favorites folder.

**Describe the solution you'd like**

- Add a new menu item 'Add to favorites' to the context menu of a folder or file in normal folders (except My Favorites and Recycle Bin). Click this menu item to create a reference of the selected folder/file (with same name) in the My Favorites folder.
- Add a new menu item 'Remove from favorites' to the context menu of a folder or file in My Favorites folder. Click this menu item to delete this reference (not move to the recycle bin folder)

**Environment**
SAS Viya

**Comment by boyce-w** [comment]
Hi @skyeaussie, I developed a prototype of this feature, here is the screenshot. I'm wondering do you need different icons for the references in the My Favorites folder to make the reference looks distinguishing with the resource items
![image](https://github.com/sassoftware/vscode-sas-extension/assets/96557225/4b8c1894-a9b8-4ce8-b403-54a79dcb78f4)

**Comment by boyce-w** [comment]
Hi, @skyeaussie @crlewi , I added some UI text in this feature, please help review, thanks.

- Menu item text:
-- Add to favorites
-- Remove from favorites
- Generic error message:
-- Unable to add the item to My Favorites.
-- Unable to remove the reference.

**Comment by crlewi** [comment]
@boyce-w updated text below. Thanks!

Menu item text:
-- Add to My Favorites
-- Remove from My Favorites
Generic error message:
-- The item could not be added to My Favorites.
-- The item could not be removed from My Favorites.
