### ISSUE TITLE
How do I configure Viya 3.5 

### ISSUE THREAD

**Issue by bmorse61** [sassoftware/vscode-sas-extension#30]
How do I configure Viya 3.5 clientID, secret code, access token etc?  
I went by https://blogs.sas.com/content/sgf/2021/09/24/authentication-to-sas-viya/
Couldn't get it working.  step 5 fails, syntax error.  Is there a step by step somewhere in this channel for configuring Viya to accept connections from VSCode users?   struggling ..

**Comment by jefurbee** [comment]
Hi @bmorse61. From the blog post you linked, you should use the access token generated in Step 4. Put the contents of the access token in a file and use the "Token File" value, in your profile in the settings.json file, to point to the file location.

Profile creation is outlined in the [Profiles section of the GitHub documentation](https://github.com/sassoftware/vscode-sas-extension#profiles).

**Comment by scnwwu** [comment]
With v0.1.1, now you only need step 1 and 2 in the blog post to generate a client ID/secret for Viya 3.5. Please refer to the latest README.

**Comment by scnwwu** [comment]
No user feedback for a while. Closing.
