### ISSUE TITLE
After login, libraries view fails to load with "Request failed with status code 406".

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/vscode-sas-extension#300]
**Describe the bug**
After logging with auth code, the sas content view populates correctly with folder and files, but the library view is empty and the error `Request failed with status code 406` appears.

**Steps to reproduce**

1. Login
2. See the error

**Expected behavior**
To see the libraries and datasets.

**Screenshots**
N/A

**Environment (please complete the following information):**
Client OS: macos
Extension version: 0.1.15
SAS version: Viya 3.5

**Additional context**
N/A

**Comment by scnwwu** [comment]
Hi, I didn't reproduce it. A couple of questions for us to better understand the problem.
Are you able to run SAS code successfully?
Are you still getting the error if pressing the "refresh" icon on the library view?
Would you click `Help > Toggle Developer Tools` from the top menu and see if any detailed error in it?
What's your VS Code version?
Are you using a Language Pack in your VS Code? If so, what language is it?
Thanks.
