### ISSUE TITLE
DataViewer does not keep column names at the top as always visible

### ISSUE THREAD

**Issue by bruno-mueller-sas** [sassoftware/vscode-sas-extension#307]
Keep the column names always visible while scrolling.

Having a row number would be nice.

**Comment by scottdover** [comment]
Hi @bruno-mueller-sas! Thanks for the feedback 😊. I think your suggestions make a lot of sense. I'll add this to the list of improvements we're planning for the data viewer.

**Comment by scottdover** [comment]
This will be taken care of as part of https://github.com/sassoftware/vscode-sas-extension/issues/308
