### ISSUE TITLE
DataViewer improvements

### ISSUE THREAD

**Issue by gygabyte017** [sassoftware/vscode-sas-extension#308]
**Is your feature request related to a problem? Please describe.**
Explore a table with current DataViewer is a little bit limited.

**Describe the solution you'd like**
It would be very nice to enrich the DataViewer with:
- show rows count
- show the first "column" with the row number
- provide data pagination and / or an indicator of current row number over the total number of rows
- show the classic sas icons on the left of columns title indicating the column type (numeric, string, etc)
- provide the possibility to sort columns by clicking on them
- provide the possibility to write a filter expression which applies temporarily to the table
- provide the possibility to copy the table to clipboard (if it's small) and / or exporting it to csv / xlsx in Sas Content and / or in the local filesystem in vscode

**Additional context**
I understand that's a lot of work, I just wanted to list what I would find very very useful.

**Comment by scottdover** [comment]
Thanks for your suggestions, @gygabyte017. We'll consider these as we continue to improve the data viewer :)

**Comment by scottdover** [comment]
Looking over this list, there are a few that have been taken care of in https://github.com/sassoftware/vscode-sas-extension/pull/395. Those are:
 - Keep the column names always visible while scrolling.
 - show the first "column" with the row number
 - show the classic sas icons on the left of columns title indicating the column type (numeric, string, etc)

These issues remain:
- show rows count
- provide data pagination and / or an indicator of current row number over the total number of - rows
- provide the possibility to sort columns by clicking on them
- provide the possibility to write a filter expression which applies temporarily to the table
provide the possibility to copy the table to clipboard (if it's small) and / or exporting it to - csv / xlsx in Sas Content and / or in the local filesystem in vscode
