### ISSUE TITLE
Clicking on Folder in SAS Content results in "Request failed with status code 500"

### ISSUE THREAD

**Issue by ChristianGroessinger** [sassoftware/vscode-sas-extension#328]
**Describe the bug**

**Steps to reproduce**

1. Go to SAS Explorer
2. Click on 'SAS Content' 
3. another Click on Folder Users

**Expected behavior**
Same behavior like SAS Studio. There I can see the subfolders. I tried a user with admin role and a user with restrictions to a certain Server Context. Same behavior

**Screenshots**

![Screenshot 2023-06-07 at 08 35 38](https://github.com/sassoftware/vscode-sas-extension/assets/56793408/7e30d500-826e-477f-839d-3f6b8b3fa158)

**Environment (please complete the following information):**
Client OS: MacOS 13.3.1
Extension version: [v0.1.5]
SAS version: [Viya 2023.03]

**Additional context**
It is possible to create a file on Users folder, but it is not possible to see it in the Explorer

**Comment by ChristianGroessinger** [comment]
Profile looks like this:
"profiles": {
         "groessichr@panda-q-pacc": {
                "connectionType": "rest",
                "endpoint": "https://panda-q.bmf.gv.at",
                "context": "Compute Server pacc",
                "clientId": "groessichr2",
                "clientSecret": "xxxxxxxxx"
            }
}
I'am getting this error right after login. 

the client is registered via rest api like this:
payload = {"client_id": client_id, 
        "client_secret": client_secret,
        "access_token_validity": "31536000",
        "scope": ["openid", "*"], 
        "authorized_grant_types": ["authorization_code", "refresh_token"],
        "redirect_uri": "urn:ietf:wg:oauth:2.0:oob"
}

**Comment by scottdover** [comment]
Hey @scnwwu . I'm wondering if you happen to know what might be going on in this case?
