### ISSUE TITLE
Local/Remote IOM connection - support for Content Navigation, Libraries, and/or the Data Viewer.

### ISSUE THREAD

**Issue by nathan-lindstedt** [sassoftware/vscode-sas-extension#347]
**Is your feature request related to a problem? Please describe.**
Currently, it appears that only a Viya connection supports content navigation, libraries, and the data viewer. It would be nice if some comparable baseline of support could be added to allow for tables generated by a local connection to be viewed in the data viewer.

**Describe the solution you'd like**
If feature parity is possible, that would be the ideal. However, if it's not possible due to technical limitations, perhaps a more limited solution can be achieved to allow for viewing tables created during a SAS local connection session in the data viewer.

**Environment**
SAS 9.4 (local)

**Comment by clangsmith** [comment]
Closing as duplicate, since this is now tracked in two separate tickets.
