### ISSUE TITLE
Can't close session when using remote server in local COM

### ISSUE THREAD

**Issue by ShuguangSun** [sassoftware/vscode-sas-extension#349]
**Describe the bug**
I have server machine with SAS OA with ITC and I use VScode in a local PC with local COM profile. The host IP is added to the profile and it can connect to the server and submit the code. However it can't find the html5 file because the file is on the server machine and VScode just get file name wich local style, e.g., `C:\Windows\TEMP\SAS Temporary Files\_xxx_xxx_\Prc2\sashtml.htm`. It blocks vscode to close the SAS session.
There should be wary to stop SAS or the extension, if the output html5 file is not accessable.

**Environment (please complete the following information):**
Client OS: Windows 11 in a local PC
Extension version: v1.0.0
SAS version: SAS 9.4M7 from OA in a server machine

**Additional context**
Maybe we can return the content of output html5 and log, and write a temporary output and log file in the local machine.

**Comment by scnwwu** [comment]
@ShuguangSun, can this one be closed now with IOM support added with #592?

**Comment by ShuguangSun** [comment]
Yes. It can be closed.

**Comment by ShuguangSun** [comment]
Yes. It can be closed.
