### ISSUE TITLE
Can't use `$` in local COM

### ISSUE THREAD

**Issue by ShuguangSun** [sassoftware/vscode-sas-extension#356]
**Describe the bug**
`format make $10.;` will be submitted as `format make .;`. It seems `$10` will be omitted.

**Steps to reproduce**

1. Create a local COM profile
2. Create a SAS file with 

```sas
proc print data=sashelp.cars; 
    format make $10.;
run;
```

3. run sas code

```
6          proc print data=sashelp.cars;
7              format make .;
                           _
                           22
                           200
ERROR 22-322: Syntax error, expecting one of the following: a name, a format name, ;, -, :, _ALL_, _CHARACTER_, _CHAR_, _NUMERIC_.  
ERROR 200-322: The symbol is not recognized and will be ignored.
```

**Environment (please complete the following information):**
Client OS: windows 2019
Extension version: 1.0.0
SAS version: 9.4M7 from OA

**Comment by smorrisj** [comment]
The $ symbol in powershell are a reserved symbol. I suspect that the code string will need to replace this with escaped versions in the $code parameter (script.ts line 76). It would probably be good to add code to the powershell script Run function to do this before passing the code string into SAS.LanguageService.Submit

**Comment by smorrisj** [comment]
If the above doesnt work, could also consider adding it to the com connection provider itself:

`    //write an end mnemonic so that the handler knows when execution has finished
    const codeWithEnd = `${codeWithODSPath}\n%put ${endCode};`;
    const codeToRun = `$code=@"\n${codeWithEnd}\n"@\n`;`

codeToRun could be augmented to do the escaping in addition.

**Comment by sasutils** [comment]
A better title would be cannot use $ in SAS code.  It is "eating" any token that starts with $.

**Comment by ShuguangSun** [comment]
`%put "ab'c";` not work as well.

**Comment by ShuguangSun** [comment]
> If the above doesnt work, could also consider adding it to the com connection provider itself:
> 
> ```ts
>  //write an end mnemonic so that the handler knows when execution has finished
>  const codeWithEnd = `${codeWithODSPath}\n%put ${endCode};`; 
>  const codeToRun = `$code=@"\n${codeWithEnd}\n"@\n\`;  
> ```
> 
> codeToRun could be augmented to do the escaping in addition.

It seems breaking the quotation.

I also tried 
```ts
const codeToRun = `$code=@'\n${codeWithEnd}\n'@\n`;  
```
It can solve the `$` issue.

But it has the problem with `'` sometimes. 
- `%put "ab'c";`  dose'nt work
- `%put 'abc';` works fine.

**Comment by ShuguangSun** [comment]
Below works for me
```ts
      //write an end mnemonic so that the handler knows when execution has finished
      const codeWithEnd = `%put \`'--vscode-sas-extension-code-beginning--\`';\n${codeWithODSPath}\n%put \`'--vscode-sas-extension-code-end--\`';\n%put ${endCode};`;
      const codeToRun = `$code=@'\n${codeWithEnd}\n'@\n`;
```

- Change `@"..."@` to `@'...'@` fix the `$` escape problem
- Add `%put \`' \`';` at the beginning and end of the code to avoid unblanced `"` or `'` in the code
