### ISSUE TITLE
Job running for longer than 60 seconds results in an error.

### ISSUE THREAD

**Issue by JosephDHenry** [sassoftware/vscode-sas-extension#36]
Currently code that takes longer than 60 seconds results in an error in vscode, but the SAS code will continue to run. 
The extension should allow for executions of longer than 60 seconds.

This is code that will show the error.

`
data _null_;
n=0;
 do while (n<62);
   put n=;
   x=sleep(1,1);
   n+1;
 end;
run;
`

**Comment by Zhirong2022** [comment]
@JosephDHenry 
I tried to use the code below to run in the formal released VAC SAS extension. I did not catch any error. I am sure if I missed something other steps? 
data _null_; n=0; do while (n<62); put n=; x=sleep(1,1); n+1; end; run;

**Comment by 2TomLi** [comment]
The fix has been included in release 0.1.2.
