### ISSUE TITLE
It is not necessarily to indent in certain case with code typing

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#363]
**Describe the bug**
Install the SAS extension base on the official release. Typing some SAS code, it can make some improvements to avoid indenting other than disable it. 

**Steps to reproduce**

1.Create a new SAS file
2.Type some code below

proc contents data=x; run;

3.Type Enter

**Expected behavior**
No code indentation in such scenario

**Screenshots**
![image](https://github.com/sassoftware/vscode-sas-extension/assets/121005702/3cd2e535-b6b7-4584-ad78-8f030b7dccfb)

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v1.0.0]

**Comment by jingjiajie** [comment]
I added a pull request to resolve this issue. https://github.com/sassoftware/vscode-sas-extension/pull/396
