### ISSUE TITLE
Focus should not change (should stay in the editor) after code runs

### ISSUE THREAD

**Issue by JosephDHenry** [sassoftware/vscode-sas-extension#37]
When you hit submit, the results window becomes active.
The SAS window should remain active as that was the active editor when the code was summited.

**Comment by clangsmith** [comment]
I agree strongly, focus should stay in the editor when you submit code (whether by clicking the running man icon on the toolbar or by pressing one of the shortcut keys (F3 or F8). Currently (in v0.1.2), I see focus moving into the Output window when I submit. This disrupts my flow as I frequently use the keyboard to navigate in the editor, make changes, submit, and want to continue navigating and editing without having to move focus back to the editor.

**Comment by 2TomLi** [comment]
The bug has been fixed in the v0.1.2 release.

**Comment by 2TomLi** [comment]
> This does not appear to have been fixed to me. As I commented above, I am still seeing focus move out of the editor into the Output window in v0.1.2 after submitting code. When I press the up/down arrow keys once the submission is complete, it is navigating in the Output window, not in the code editor. Re-opening. Please let me know if you are seeing something different.

You are correct, I was attempting to close #36, I opened many tabs in my browser, then closed this one by mistake.

**Comment by scnjdl** [comment]
This is fixed in #444, close it as completed.
