### ISSUE TITLE
Can I integrate the monaco editor?

### ISSUE THREAD

**Issue by XiaoPengYouzzZ** [sassoftware/vscode-sas-extension#379]
Hello! To my knowledge, vscode seems to be written based on the monaco editor, but monaco editor currently does not support the sas language, which means it dose not provide a sas language pack. So if I want to use the monaco editor in the project and use the sas language, I must register the sas language through the monaco. I would like to know if this vscode extension program can provide assistance for my current work, or has any seniors ever done this job? Looking forward to your reply, thank you very much!

**Comment by scnwwu** [comment]
This project implements [Language Server Protocol](https://microsoft.github.io/language-server-protocol/). You can build a SAS language server from it. If you have a language client for Monaco editor (for [example](https://github.com/TypeFox/monaco-languageclient)), you'll be able to connect to a language server.
This is out of the scope of this project. Closing.
