### ISSUE TITLE
Is there a way to view SAS datasets in VS Code?

### ISSUE THREAD

**Issue by asjohans** [sassoftware/vscode-sas-extension#383]
I cannot find a way to view SAS datasets within VS Code and I cant find any info about it. Does anyone know a way?

SAS 9.4 locally installed

Thanks
AJ

**Comment by nathan-lindstedt** [comment]
It's only supported by with a Viya connection currently. I opened an issue for this a few weeks ago.

https://github.com/sassoftware/vscode-sas-extension/issues/347

**Comment by scnwwu** [comment]
Closing as dup
