### ISSUE TITLE
SAS code formatter

### ISSUE THREAD

**Issue by Pulpanj** [sassoftware/vscode-sas-extension#390]
**Is your feature request related to a problem? Please describe.**
This is a feature request.

**Describe the solution you'd like**
Provide SAS code formatter (aka usual VSC Shift_Alt_F ).

**Describe alternatives you've considered**
SAS code formatting is available in SAS Enterprise Guide, I am not sure how complex is port to VSC extension, knowing that SAS code formatting is not straightforward.

**Additional context**

**Environment**
Any version

**Comment by scnjdl** [comment]
There is already a feature issue for formatting,[issue-28](https://github.com/sassoftware/vscode-sas-extension/issues/28)

**Comment by Pulpanj** [comment]
Thanks - I did not find that feature request ;-)

**Comment by scnwwu** [comment]
Closing as dup
