### ISSUE TITLE
It cannot show the correct result anymore in certain circumstance with connection type SAS9.4(local-COM)

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#408]
**Describe the bug**
Install the SAS extension base on the latest Main branch. Switch to a profile with connection type 'SAS9.4(local-COM)',try to run some code. Suppose there is something wrong with the code running, correct the code and try to run it again. It cannot show the correct result anymore.  

**Steps to reproduce**
1. Create a new SAS profile with connection type SAS9.4(local-COM) or switch to a profile with connection type SAS9.4(local-COM)
2. Run some code below
	proc sgplot da=sashelp.class;
	histogram age;
	run;
3. It will show syntax Error in the log 
4. Correct the code
5. Run the code again, it will not show the correct output as expected

**Expected behavior**
It can show the correct result 

**Screenshots**
![image](https://github.com/sassoftware/vscode-sas-extension/assets/121005702/5e23c7ca-396c-42ea-9274-ee4414d79eee)

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v01.0.0]

**Comment by gah-bo** [comment]
![image](https://github.com/sassoftware/vscode-sas-extension/assets/64602073/4b0135d9-fd3a-4195-8dd2-f6e7d4ef83b8)

I am having a similar issue; code i can run in SAS gives me errors in VS Code. Also I can't even get a print statement to work as expected...

**Comment by Zhirong2022** [comment]
I cannot reproduce the issue in the latest main branch.

**Comment by scnwwu** [comment]
Fixed by #592
