### ISSUE TITLE
It is not necessary to show result window if having no any ODS output with connection type SAS9.4(local-COM)

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#410]
**Describe the bug**
Install the SAS extension base on the latest Main branch. Switch to a profile with connection type 'SAS9.4(local-COM)',try to run some code. It is not necessary to show result window if having no any ODS output. Please refer the raised the issue https://github.com/sassoftware/vscode-sas-extension/issues/46.

1. Create a new SAS profile with connection type SAS9.4(local-COM) or switch to a profile with connection type SAS9.4(local-COM)
2. Run some code below
	proc options; run;

**Expected behavior**
No need to show result window if having no any ODS output

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v1.0.0]

**Comment by scnwwu** [comment]
It has been resolved by #475
