### ISSUE TITLE
Convert notebook to flow

### ISSUE THREAD

**Issue by sahbic** [sassoftware/vscode-sas-extension#446]
**Is your feature request related to a problem? Please describe.**
I would like to be able to share my SAS notebook code with colleagues using SAS Viya GUI and industrialize it in SAS Studio.

**Describe the solution you'd like**
Right click on a SAS notebook and convert it to a flow, then use it in SAS Studio: share, modify, schedule etc..

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Environment**
SAS Viya

**Comment by clangsmith** [comment]
Disclaimer: While you can inspect the SAS Studio Flow JSON format (for example, by opening a .flw file in an editor), it is not a publicly documented or publicly supported format/schema. It is still internal/proprietary. We strive to keep the Flow format backwards compatible, but there is a possibility that future changes to the internal model could break this “convert SAS Notebook to SAS Studio Flow” feature in VS Code, requiring additional changes to the SAS extension to fix this feature. In other words, when you are using the Flow format/schema directly (as in this feature), you are using it as-is and at your own risk.
