### ISSUE TITLE
No HighContrast theme for the tables

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#448]
**Describe the bug**
Install the SAS extension base on the official release. Specify the color theme as 'SAS High Contrast', open a table at Library section. No HighContrast theme for the table.

**Steps to reproduce**
1. Sign in with a valid profile
2. Specify the color theme as 'SAS High Contrast' through Manage->Themes->Color Theme
3. Open a table at Library section 

**Expected behavior**

**Screenshots**
![image](https://github.com/sassoftware/vscode-sas-extension/assets/121005702/02a01f37-e654-4aa3-a949-9f288d22351b)

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v1.1.0]

**Comment by clangsmith** [comment]
window.activeColorTheme.kind will return ColorThemeKind.Light, Dark, HighContrast, or HighContrastLight. Can see how we are using it in PR #473 to pick an ODS style that reasonably matches VS Code color theme.
