### ISSUE TITLE
Refreshing the vscode window will result in a new session being created.

### ISSUE THREAD

**Issue by JosephDHenry** [sassoftware/vscode-sas-extension#45]
If the window is reloaded (refresh page in browser OR command "Developer: Reload Window") the session will be recreated instead of reused.

I would expect the session that was active before be used again.

**Comment by scottdover** [comment]
@JosephDHenry I believe this has been resolved, right? Or are you talking about compute session?

**Comment by scnwwu** [comment]
I believe @JosephDHenry meant compute session. It's addressed in #175 but not publicly documented.
