### ISSUE TITLE
Missing Intellisense suggestions in LSP

### ISSUE THREAD

**Issue by smorrisj** [sassoftware/vscode-sas-extension#457]
**Describe the bug**
The following symbols are missing or inaccurate when using intellisense provided through the language server:

- sleep function
- rannor function
- Proc PCA, random option is missing as a valid value for  method (I dont see random defined in the official documentation, might need to speak to Ning Kang for this one)
- LSP Doc for KCLUS does not match SAS documentation

**Comment by scnwwu** [comment]
Hover help content for PROC KCLUS has been updated

**Comment by scnwwu** [comment]
All issues here fixed in main branch now.
