### ISSUE TITLE
Results window does not support SGMAP output

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#471]
**Describe the bug**
Try to run a SGMAP example, it cannot show the output graph in result window. However it will work well with the workaround, add the the code (ods html5 options(bitmap_mode="inline");) on the top of the sample code.

**Steps to reproduce**
1. Sign in with a valid profile(Viya connection)
2. Run the SGMPA example code below
data katrina;
    format datetime datetime18.;
    informat datetime datetime18.;
    infile datalines dlm=',';
    input datetime lat long wind;
    datestring=substr(put(datepart(datetime),date9.),1,5);
 datalines;
 23AUG2005:18:00:00,23.1,-75.1,30
 24AUG2005:06:00:00,23.8,-76.2,30
 25AUG2005:06:00:00,26.1,-78.4,50
 26AUG2005:06:00:00,25.4,-81.3,65
 27AUG2005:06:00:00,24.4,-84,95
 28AUG2005:06:00:00,25.2,-86.7,125
 29AUG2005:06:00:00,28.2,-89.6,125
 30AUG2005:06:00:00,34.1,-88.6,40
 31AUG2005:06:00:00,40.1,-82.9,25
 ;
 run;
 
 title1 'Hurricane Katrina (2005)';
 proc sgmap plotdata=katrina;
    openstreetmap;
    series x=long y=lat / 
       lineattrs=(color=red thickness=2)
       legendlabel='Storm Track';
    bubble x=long y=lat size=wind /
       fillattrs=(color=blue transparency=.9)
       datalabel=datestring datalabelpos=left
       datalabelattrs=(color=red size=10)
       legendlabel='Relative Wind Speed';
 run;

**Expected behavior**
The output image can be shown properly in result window

**Screenshots**
![image](https://github.com/sassoftware/vscode-sas-extension/assets/121005702/ef1dcf2f-b74e-43d0-ad3c-2bb081019a1a)

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v1.2.0]

**Comment by scnwwu** [comment]
An immediate workaround is to add `ods html5 options(bitmap_mode="inline");` at top of your code.

**Comment by clangsmith** [comment]
The reason the image is unresolved is that the ODS HTML5 destination links image files created by procs by default (using <img> tag), but the image file does not exist at the path location referenced in the .html file. For example, here is the <img> tag in the html: 
<img style="height: 480px; width: 640px" alt="The SGMap Procedure" src="SGMap.png"/>

So, it is looking for a file named SGMap.png in the same location as the html file (a relative path), but it doesn't exist. Therefore, another option would be to download any resultant image files along with the html file and make sure they are in the proper relative locations. However, I think it is better (simpler) to put the images inline, similar to how SAS Studio and EG do.
