### ISSUE TITLE
Get output html when using remote server in local COM

### ISSUE THREAD

**Issue by ShuguangSun** [sassoftware/vscode-sas-extension#493]
**Is your feature request related to a problem? Please describe.**
When I use a remote server via COM, e.g., via COM with a remote host url, it cant get the output html because the returned path to the html file is a a "local" path in the remote server. So vscode can't find the file in the local PC.  

**Describe the solution you'd like**
Return the content of html file just we do for the log. For example, we can echo the content of the html file to the console and then return it from powershell. In this case, the picture should be embed in the html file.

**Environment**
SAS version 9.4 in remote server from SAS OA

**Comment by scnwwu** [comment]
@ShuguangSun, can this one be closed now with features added by #592?

**Comment by ShuguangSun** [comment]
Yes.
