### ISSUE TITLE
No autocomplete list with code typing 

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#497]
**Describe the bug**
Open VSC SAS Extension, type some code, it has no autocomplete list with code typing.

**Steps to reproduce**
1. Open VSC SAS Extension
2. Type code below:
   data _null_;
   call s

**Expected behavior**
The autocomplete list is there if trying to type 's'

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v1.2.0]

**Comment by scnwwu** [comment]
Regression introduced by #430

**Comment by Zhirong2022** [comment]
The autocomplete list is shown as expected.
