### ISSUE TITLE
SAS Log color-coding in Output Window for SAS 9 IOM connections

### ISSUE THREAD

**Issue by PaulShannon-KatalyzeData** [sassoftware/vscode-sas-extension#506]
SAS program logs are written to the VSCode output window in plain text, with no colour-coding for Errors, Notes and Warnings. Colouring of the Output channel is supported in VSCode from  [v1.66 (March 2022)](https://code.visualstudio.com/updates/v1_66#_output-channel-with-custom-language-id).

> In this milestone, we have finalized the [createOutputChannel API](https://github.com/microsoft/vscode/blob/dc2f5d8dd1790ac4fc6054e11b44e36884caa4be/src/vscode-dts/vscode.d.ts#L9415) to create an output channel with custom language ID. This will allow you to contribute token or syntax coloring and CodeLens features to your Output channel by passing a language ID

Suggest development for standard SAS colouring based on the theme applied (i.e.: dark/light theme etc.).

Further, the ability to configure custom highlights for customer-specific log entries perhaps using RegEx would be advantageous. For example: search for "variable is uninitialized" note and highlight with a user-defined colour.

**Comment by scnwwu** [comment]
Hi @PaulShannon-KatalyzeData, the SAS Log is colored for Viya connection and SAS themes.
Are you requesting for non-SAS themes or non-Viya connections?

**Comment by PaulShannon-KatalyzeData** [comment]
Hi,

I Haven’t seen the extension with Viya yet, I’m using it with SAS 9.4.

Many thanks,
Paul

**Comment by scnwwu** [comment]
OK. I updated the issue title.
For SSH connection it is challenging. Only plain text is exchanged through SSH. RegEx may not work well as error/warning/info messages can across multiple lines and there's no explicit ending.
For COM/IOM it should be feasible.

**Comment by PaulShannon-KatalyzeData** [comment]
Hi,

I’m not overly up to speed on VSCode extensions, but I believe they are written using NodeJS, something I’m not massively familiar with.

My thought RE: the ability to use RegEx would be that a user could provide some patterns in a JSON file, and these would be parsed locally within VSCode, meaning plain text read from SAS would be suitable.

However, if that’s not a realistic approach, I think standard colouring of logs would help encourage many of our clients to drop the use of Enterprise Guide in favour of VSCode.

Many thanks,
Paul

**Comment by QuentinMcMullen** [comment]
+1 for needing log coloring when connected to local SAS 9.

Even something simple based on first word of line being ERROR, WARNING, or NOTE, and stopping the coloring at the first CR/LF would  be fine.  If errors aren't RED, they're hard to spot.  On PC SAS and EG I make them RED REVERSE, so you see a big red bar, with the error message text in white.
