### ISSUE TITLE
[Table Viewer] Placeholder for improvements

### ISSUE THREAD

**Issue by scottdover** [sassoftware/vscode-sas-extension#532]
**Describe the solution you'd like**
This is a placeholder for general dataviewer improvements. Here's a list of all the things I'll be researching and maybe implementing as part of this:
 - [ ] Overflow menus for column headers
 - [ ] Click to sort headers
 - [ ] Filtering and sorting of data
 - [ ] Display of # columns/rows
 - [ ] Context menus for cells to copy data/etc

**Comment by phytomosaic** [comment]
Users may also wish to alter font size and cell color.  Thank you for your great work on this, every improvement you make increases uptake.

**Comment by snlwih** [comment]
Have split this out in specific smaller feature requests: 

1. #788 
2. #791 
3. #916 
4. #1318
