### ISSUE TITLE
Would like focus to stay in the program when a program is run

### ISSUE THREAD

**Issue by clangsmith** [sassoftware/vscode-sas-extension#548]
**Is your feature request related to a problem? Please describe.**
Currently, when you run a SAS program (via F3, F8, or the toolbar button), focus moves out of the SAS program into the OUTPUT window where the log is displayed. Therefore, if I want to continue to make changes to the program (common), I have to explicitly move focus back to the program window each time. This is annoying.

Note: This is also how Python behaves. If I press F5 or Ctrl+F5 in a Python program, the output is displayed in the Terminal window, but focus stays in the Python editor, so I can quickly continue coding.

**Describe the solution you'd like**
I would strongly prefer focus to stay in the program editor when a program is run, so I can continue quickly making code changes, submitting the code, and see the log and results for my latest changes without disruption.

**Describe alternatives you've considered**
We could potentially add a user option (similar to what we did in EG, and potentially in Studio) if users request the ability to put focus elsewhere after a run. For example, if there is a resultant error, they may want focus to automatically go there in the log. For now though, I think we should just change it to keep focus in the editor, since the more common desire.

**Additional context**
When the "SAS>Results: Side By Side" option is unchecked, the Results tab should still be activated, thus moving focus out of the editor. This is reasonable, since both in the same tab group in this case.

**Environment**
SAS Viya 2023.09

**Comment by scnwwu** [comment]
duplicated to #37
