### ISSUE TITLE
Cannot change active profile when activeProfile points to non-existing profile name

### ISSUE THREAD

**Issue by snlwih** [sassoftware/vscode-sas-extension#582]
**Describe the bug**
Cannot change active profile in the UI after having edited settings.json which resulted in the activeProfile tag pointing to a non-existent profile. The UI shows the list of profiles and allows me to select one, but that selection is not activated. Of course this is a user error, but still would have expected the UI to allow me activate a profile from the selection list. 

***Note***: Editing settings.json again and fixing the value of the activeProfile tag to point to a profile that exists results in the UI behaving again as expected. 

**Steps to reproduce**
1. Edit settings.json and change activeProfile to "DoesNotExist". (this mimics changing the name of the profile that is currently used by the activeProfile tag)
2. Open VSCode
3. Open .sas file
4. In the status bar it says "No Profile"
5. Click on "No Profile" and select an existing profile
6. The selection is not activated and the status bar still says "No Profile". 
7. Same happens when using the command palette and choosing "SAS: Switch Current Connection Profile" 

**Expected behavior**
The user selected profile to become the active profile 

**Environment (please complete the following information):**
Client OS: [Windows 10 (19045.3448)]
Extension version: [v1.4.1]
SAS version: [SAS 9.4]

**Comment by snlwih** [comment]
Low priority, but still wanted to have reported it.

**Comment by clangsmith** [comment]
I am not able to reproduce using the steps above. When I select an existing profile, it does take effect. I'm using v1.4.1.

I assume in step #1, you are editing the settings.json file outside of VS Code? If I edit the settings.json file in VS Code and change the activeProvider value to a profile that does not exist, when I save the settings.json file, the activeProvider value is immediately set to "". So, I edited the settings.json outside of VS Code, then opened VS Code, followed your steps, and each time am able to select an existing profile.

I'm not sure what the difference is between the behavior you are seeing and I am seeing. Would be curious to know if others are able to reproduce.

**Comment by Zhirong2022** [comment]
I cannot switch profiles successfully if the settings.json file is in open status. So, it is better to check the status of settings.json file to make sure it is saved properly.

**Comment by snlwih** [comment]
User error! Somehow there was curly bracket missing after one of my profile definitions. Adding a curly bracket fixed everything. Thanks to @clangsmith for helping me with this!

Should there have been an error/warning visible in the VSCode UI somewhere to inform the user that their settings.json has incorrect syntax, or somethign along those lines?
