### ISSUE TITLE
Coding issue of the log of local profile

### ISSUE THREAD

**Issue by ShuguangSun** [sassoftware/vscode-sas-extension#583]
**Describe the bug**
When I use the local profile (COM), if the code contains non-ascii code (e.g. Chinese or other UTF8 symbols), it would 
1. can't recognized the char correctly in the code, and SAS would raise error
2. If put those chars in the log, VScode would report error like "FlushLog Error"

**Steps to reproduce**

Code example 1: `ERROR: The name '�'n is not a valid SAS name.`
```sas
data _null_;
    put "啊";
run;
```

Code example 2: `Flush log Error`
```sas
data trt;
  input trt $20.;
  cards;
紫杉醇
多柔比星脂质体
拓扑替康
;
run;

data _NULL_;
  set trt;
  put (trt)(=);
run;
```

Code example 3: 
```sas
data trt;
  input trt $20.;
  cards;
紫杉醇
多柔比星脂质体
拓扑替康
;
run;

proc print data = trt noobs;
run;
```

It seems the data is not correct:
```
<html>
<body>
<!--StartFragment-->

trt
--
绱潐閱?
澶氭煍姣旀槦
鎷撴墤鏇垮悍

<!--EndFragment-->
</body>
</html>
```

**Expected behavior**
Put the char correctly in the log window.

**Environment (please complete the following information):**
Client OS: Windows 2019
Extension version: 1.4.1
SAS version: 9.4

**Additional context**

The COM script relies on powershell. It seems the coding the code and log is not well handled. Maybe we can use utf-8 anyway.

**Comment by Zhirong2022** [comment]
@ShuguangSun , I cannot reproduce the issue in my testing environment. Perhaps, you did not configure the language for local 94. Please find the .cfg file at  C:\Program Files\SASHome\SASFoundation\9.4 to make sure zh is set. 
-config "C:\Program Files\SASHome\SASFoundation\9.4\nls\zh\sasv9.cfg"
![image](https://github.com/sassoftware/vscode-sas-extension/assets/121005702/9989ff03-bfdd-4617-b190-06b973c3de1a)

**Comment by ShuguangSun** [comment]
Thanks. My SAS (local/COM) server's encoding is UTF-8 and I can't change it. So I tried to change the encoding of remote poweshell to utf-8 by put `chcp 65001` in '$profile'.  Now example 1 and 3 are well solved.

The exmple 2 still get 'Flush log Error' message. I'll have other tries.

**Comment by ShuguangSun** [comment]
Solved example 2 flush log error by adding `"locale=zh_CN"` to `sasOptions`.

**Comment by ShuguangSun** [comment]
I think the key is to make the encoding of SAS session and powershell the same.
