### ISSUE TITLE
Matching parentheses of functions are not highlighted correctly 

### ISSUE THREAD

**Issue by Zhirong2022** [sassoftware/vscode-sas-extension#586]
**Describe the bug**
Open VSC SAS Extension base on the Main Branch, editor incorrectly highlights matching parentheses of functions containing quoted parentheses among arguments. 

**Steps to reproduce**
1. Open VSC SAS Extension
2. Type SAS code below
data _null_;
    x=finfo('fileid(');

**Expected behavior**
The matching parentheses of functions can be highlighted as expected (NOVACOMMONS-14048)

**Screenshots**
![image](https://github.com/sassoftware/vscode-sas-extension/assets/121005702/f9caa730-b14a-4b74-9ab3-eda2013431c5)

**Environment (please complete the following information):**
Client OS: [e.g. Windows 11]
Extension version: [e.g. v1.4.1]

**Comment by scnwwu** [comment]
Fixed in v1.9.0
