### ISSUE TITLE
Outline does not capture steps within macro definitions

### ISSUE THREAD

**Issue by thays42** [sassoftware/vscode-sas-extension#6]
Any steps written within a macro definition do not appear in the Outline. Since macros are a way to group and reuse steps, it would be nice if the outline could show steps and macros within a macro definition.

To replicate, place the following code in a new SAS script:

```sas
data work.class;
    set sashelp.class;
run;

proc sort data=work.class;
    by age;
run;

%macro foo();
    data work.class;
        set sashelp.class;
    run;
    
    proc sort data=work.class;
        by age;
    run;
%mend;
```

The Outline looks like this:

![image](https://user-images.githubusercontent.com/815509/170338779-4fd51e04-3e3a-4653-a0a2-bc16ea073afb.png)

It would be great if it could look something like this (mocked up in paint):

![image](https://user-images.githubusercontent.com/815509/170338901-555bb5df-e34e-435e-95a8-7423609d5d2a.png)

I am using v0.0.4 of the extension.

**Comment by cjdinger** [comment]
@thays42 I'll let the development team respond officially, but this can get tricky/impossible quickly. SAS macro language can generate any text in nearly any way and only the SAS macro processor can really reveal that structure -- at run time when all other conditions are evaluated.

For example, imagine:

```
%let step=proc means data=cars sum means;

%macro foo;
&step.
%mend;
```

What would you expect to see? Or imagine macro code that generates different steps of SAS code depending on some condition?

**Comment by thays42** [comment]
I agree that flexibility of the SAS macro language creates a lot of edge cases. This is something I have been thinking about myself when considering SAS language support for VS Code. 

I would expect the Outline to point to SAS statements that start steps. I would not expect the Outline to try to do any macro processing so that the Outline works with the code as it appears in the source file. In your example, I would expect the Outline to show a single %MACRO (ideally, it'd show %MACRO - FOO, but that's a separate issue).

There are definitely edge cases and there always will be because the macro language is so flexible. Perhaps you can establish and document a set of rules that yield a better outline than the current version offers so users know how the outline works. Perhaps there could be a setting like Outline Behavior that can be set to "Top Level" (current behavior) or "Nested" (proposed behavior).

**Comment by ShuguangSun** [comment]
I think we provide something like lsp server. Maybe we could outline based that.
Or simply as @thays42 suggested. No matter what, it is fine to treat the "proc means..." in the example above as string and no need outline or folding.

Leave decision on the code style to the user or their team.

**Comment by ShuguangSun** [comment]
Or make /*region*/ and /*endregion*/ work in macro definition.
