### ISSUE TITLE
Support for TextMate scopes

### ISSUE THREAD

**Issue by gowerc** [sassoftware/vscode-sas-extension#60]
**Is your feature request related to a problem? Please describe.**

(Apologies if my terminology is wrong I don't 100% understand this)
It looks like this extension currently only provides semantic tokens via a language server (I think). However not all themes support semantic tokens. For example the [Hop Light](https://marketplace.visualstudio.com/items?itemName=bubersson.theme-hop-light) and [Light High Contrast](https://marketplace.visualstudio.com/items?itemName=stephenwassell.light-high-contrast-theme) themes appear to only work with TextMate scopes. This results in no syntax highlighting if using these themes:
![image](https://user-images.githubusercontent.com/8447209/208146394-fb49dd9e-8e3c-4355-b89e-740757002e95.png)

**Describe the solution you'd like**
The extension should provide [TextMate scopes](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#contributing-a-basic-grammar) so all themes can provide syntax highlighting to SAS programs. 

**Describe alternatives you've considered**
At the moment if I want to keep my existing theme I have to load an [unofficial SAS extension](https://github.com/77QingLiu/vscode-SAS.tmLanguage/blob/master/syntaxes/sas.tmLanguage.json) to get syntax highlighting :(

**Comment by gowerc** [comment]
As a workaround I realised you can force theme extensions to apply syntax highlighting to semantic tokens by using:

```
    "[sas]":{
        "editor.semanticHighlighting.enabled": true
    },
```
 
 In the user settings.json.

For reference theres also a handy table that shows the automatic mappings of semantic tokens -> textmate tokens [here](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#predefined-textmate-scope-mappings)

**Comment by scnwwu** [comment]
As you can see in the unofficial extension, there will be problems to describe SAS syntax with TextMate. Semantic tokens is the only way to accurately highlight SAS syntax. As you mentioned, semantic tokens should not be a problem.
