### ISSUE TITLE
[SAS Notebook] allow displaying lengthy outputs and/or logs in a kind of scrollable or collapsible div

### ISSUE THREAD

**Issue by jbodart-argenx** [sassoftware/vscode-sas-extension#606]
**Is your feature request related to a problem? Please describe.**
Lengthy outputs in SAS notebook make it difficult to move to the next cell.

**Describe the solution you'd like**
Displaying lengthy outputs in a kind of scrollable div would make it much easier to navigate past the lengthy cell output to the next cell.

**Describe alternatives you've considered**
Alternatively, having a button or keyboard shortcut allowing to move to the top of the next cell, or to collapse the output of a specific cell, would also facilitate navigation.

**Additional context**
In addition, adding an option to either show or hide selectively the log, and/or the output, generated by an individual code cell, would be very valuable.

**Environment**
any SAS version

**Comment by scnwwu** [comment]
Are these helpful?
1. User can collapse/expand notebook cells and outputs by clicking the left bar of the cell

![image](https://github.com/sassoftware/vscode-sas-extension/assets/96556502/479381ce-e932-414b-afc9-80cb1a2e1747)

2. When cursor in the last line of a code cell, press Down Arrow key will move the cursor to the next code cell.
3. Enable `Notebook › Outline: Show Code Cells` settings, then you can navigate through cells from the Outline pane.

**Comment by jbodart-argenx** [comment]
Yes that helps, thank you.

The only thing missing is: adding an option to either show or hide selectively the log, and/or the output, generated by an individual code cell.
Indeed when a cell generates both some output and some log messages, it seems the output is shown but not the log.
Sometimes I would like to see both, sometimes only the log, sometimes only the output, sometimes neither.
This should be configurable on a cell by cell basis.

**Comment by scnwwu** [comment]
The notebook UI is provided by VS Code.

- To toggle log or ODS output display, click `...` at the side of the output and select Change Presentation.

**Comment by jbodart-argenx** [comment]
I will try it out.  Is that 'Change Presentation' only available when both log and ODS output are present for a cell, and you can choose to see either the log or the ODS output? 

Another thing: a cell can be completely collapsed or not at all.  Would it be possible to toggle and show only the first line, or the first few lines,   or a maximum of say 10 lines with a scrollbar being added when there are more than 10 lines ?

**Comment by scnwwu** [comment]
> Is that 'Change Presentation' only available when both log and ODS output are present for a cell, and you can choose to see either the log or the ODS output?

Correct

> Another thing: a cell can be completely collapsed or not at all. Would it be possible to toggle and show only the first line, or the first few lines, or a maximum of say 10 lines with a scrollbar being added when there are more than 10 lines ?

Currently no. Can be researched in future.

**Comment by snlwih** [comment]
Workaround is available by either clicking on the "..." item at top left of the cell or by clicking on the narrow bar displayed to the left of the cell to toggle display on/off. The capability to toggle log or ODS output display is described in the [SAS Notebook page in the documentation](https://sassoftware.github.io/vscode-sas-extension/Features/sasNotebook).

Limiting the display in the output/log cell to the first xxx lines with a "... more" option would be a nice-to-have. However, given the long list of feature requests we have no resources to implement this. Therefore closing.
