### ISSUE TITLE
Support for Remote SAS 9.4

### ISSUE THREAD

**Issue by gowerc** [sassoftware/vscode-sas-extension#61]
**Is your feature request related to a problem? Please describe.**

My company/department currently has licensed SAS9.4. We work on a server that we SSH into and then use the terminal `sas` command to run programs. This extension doesn't appear to currently have any support for this way of working. Current work around is just to open a sas interactive session via `sas --nodms` and have a keyboard shortcut for submitting commands to the terminal however it would be great if this way of working + sas9.4 could have formal support.

**Describe the solution you'd like**
Integration with local sas + sas9.4.

**Comment by smorrisj** [comment]
We're going to repurpose this issue to specifically target SAS 9.4 Remote Support implementation and testing of PR #134

**Comment by smorrisj** [comment]
@Sonny-W would it be possible to assign this out for verification?

**Comment by Becky-Williamson** [comment]
Tested the following scenarios:

- Create 9.4 ssh profile using VSC prompts
- Create 9.4 ssh profile manually in json
- Run SAS code connected to 9.4
- Switching between ssh and viya profiles
- Verify that Explorer pane is not displayed in when connected to 9.4
- Verify that SYSTEM options can be defined in profile

**Comment by smorrisj** [comment]
> Hey @Becky-Williamson & @smorrisj , Just wanted to say that when I tried testing this feature it looks like it doesn't work if the ssh address requires a proxy. At least within our company the main server requires a proxy entry point i.e. we have the following in our `~/.ssh/config` files:

@gowerc  thanks for testing this out. We can look into implementing support for a jump connection. If it's agreeable could we possibly track this feature in a separate issue?

**Comment by smorrisj** [comment]
> I'm afraid that the functionality isn't overly useful to my team if it can only handle batch (complete program) submissions :(. At least not in how we currently work / use SAS. Would the local sas feature being developed for #11 also have these same limitations ?

@gowerc thanks for reporting. It seems like there is possibly a bug in how the session is being handled where the work tables are not persisting. I can look into this and report back.

**Comment by smorrisj** [comment]
When I dump out the work directories in between the two runs on the same connection, I'm seeing two different directory names in /tmp. 

When I look at the run command, it's calling setup and run functions on the session every time the run button is pressed. The problem here is that for the ssh connection provider the setup function essentially reconnects to the server and starts up sas again in -nodms mode.

I think that the desired functionality we want is for it to behave closer to how interactive line mode behaves, meaning that we invoke sas once, perform 1-n commands and then exit when the close button is pressed.

**Comment by smorrisj** [comment]
Bug logged for the session issue on #155

**Comment by HwangWonYoung** [comment]
> Tested the following scenarios:
> 
> * Create 9.4 ssh profile using VSC prompts
> * Create 9.4 ssh profile manually in json
> * Run SAS code connected to 9.4
> * Switching between ssh and viya profiles
> * Verify that Explorer pane is not displayed in when connected to 9.4
> * Verify that SYSTEM options can be defined in profile

Can I get an example of creating 9.4 ssh profile in detail?

**Comment by HwangWonYoung** [comment]
@Becky-Williamson 
Is it possible using this extension when using SAS Connect over TCP/IP not ssh?

**Comment by cjdinger** [comment]
@HwangWonYoung SAS/CONNECT allows one SAS session to connect and exchange data/code/results with another SAS session. So this extension still needs to connect to a SAS session using one of the supported methods (like ssh), and then **that** SAS session could connect to another SAS session via rsubmit and other traditional SAS/CONNECT methods.

**Comment by smorrisj** [comment]
> Yup am happy for this to be a separate issue, do you want me to create it ?

@gowerc apologies for the delay. That would be great. Thanks!

**Comment by HwangWonYoung** [comment]
@cjdinger Hi, I'm trying to set up this extension using visx file because my sas is in offline environment. I downloaded file at this url(https://marketplace.visualstudio.com/items?itemName=SAS.sas-lsp), but it doesn't seem it reflects this feature(support for remote sas). Can you please check if the latest version is uploaded? Thank you in advance.

**Comment by GaryLiuTelus** [comment]
Just tested and could not connect to the remote server, and got below error when submitting SAS script:

`SSH_AUTH_SOCK not set, Check Environment Variables.`

My Environment: 

OS: Window 10
Remote server in within VPN

Extension settings:
![image](https://user-images.githubusercontent.com/39339422/232140960-fe630c70-951e-47cd-9322-332724378095.png)

Any suggestions? What value I should assign to `SSH_AUTH_SOCK` system variable?

**Comment by smorrisj** [comment]
Hi @GaryLiuTelus, see #202 for how to set this up to run on windows.

**Comment by gro1m** [comment]
> > @gowerc thanks for testing this out. We can look into implementing support for a jump connection. If it's agreeable could we possibly track this feature in a separate issue?
> 
> Yup am happy for this to be a separate issue, do you want me to create it ?

@gowerc Did you create an issue for this or did you find another way?

**Comment by shenzj1994** [comment]
Hi @smorrisj , I am having the same issue as @GaryLiuTelus and we use _username and password_ to authenticate SSH with the server.
Do we have support for this type of authentication?

**Comment by smorrisj** [comment]
@shenzj1994 currently we only support password-less authentication using public and private key pair where the private key is registered with the ssh-agent.

**Comment by scnwwu** [comment]
Additional requests tracked in separated issues, closing this one.
