### ISSUE TITLE
Provide an option to allow user to control the default placement of Results

### ISSUE THREAD

**Issue by 2TomLi** [sassoftware/vscode-sas-extension#62]
**Is your feature request related to a problem? Please describe.**
There is one thing some user has been trying to do:  To get the results to appear in the SAME tab group as the code.

**Describe the solution you'd like**
Provide a setting to allow the result output tab to show up in the same tab group with the code tab

**Describe alternatives you've considered**

**Additional context**

![777376a7-c8b5-49a3-a6a8-c505ef3b9839](https://user-images.githubusercontent.com/15733070/208176053-e2e671a7-b69b-452c-be89-0d2953975430.jpg)

**Comment by clangsmith** [comment]
I believe we will need to think this through at a higher level with @skyeaussie and @crlewi. More generically, I believe the ask is to surface options to allow users to control the default tab layout and associate the content. Right now, that includes the SAS code tab and the Results tab, but eventually it will also include an Output Data tab. We will need to think through how we want to tie all these together and present them.
