### ISSUE TITLE
SAS Output Log channel is continually focused periodically for long running executions hijacking focus from other panels while the submission runs

### ISSUE THREAD

**Issue by smorrisj** [sassoftware/vscode-sas-extension#647]
**Describe the bug**
As a user, I'd like to be able to use other panels (such as terminal) uninterrupted while waiting for my long-running SAS Program to finish its execution without losing focus.

**Steps to reproduce**

1. Run the following SAS code:
```
  data _null_;
      slept=sleep(10,1);
  run;
  
  proc print data=sashelp.cars;
  run;
  
  data _null_;
      slept=sleep(10,1);
  run;
  
  proc print data=sashelp.air;
  run;
```
2. Click on terminal and interact with the CLI.
3. Observe that as log output is flushed, focus is automatically shifted back to Output/SAS Log.
4. Click on the terminal and continue interaction.
5. Observe that subsequent log output flushes also steal focus.

**Expected behavior**
Right now we're calling "show" on the LogChannel component for every chunk/LogLine that gets flushed to the OutputChannel. This call will reveal our SAS Log Output Channel in the UI, taking focus away from whatever the user might be already doing. This will become especially annoying for programs that have heavy log output. 

Ideally there would be some profile options to allow the user to tailor the experience here.  One option to "focus log on beginning of execution" and perhaps another option to focus on the output window once execution has finished.

**Comment by scnwwu** [comment]
We're calling `outputChannel.show(true)` where the `true` parameter tells the output to NOT take focus. You can keep typing code in the editor while the log append, it won't take your focus.
It's just that the Terminal by default sits together with Output. So to just "show" the Output (not taking focus), it has to hide Terminal.
A workaround is to drag the Terminal or Output to the right side pane, so that they're separated, like
https://github.com/sassoftware/vscode-sas-extension/issues/581#issuecomment-1791818069

**Comment by snlwih** [comment]
We definitely need to provide the user with an option to tailor their experience to some extend. Supporting some settings for the SAS extension to specify if/when SAS Output or Table Viewer (once we have that added for IOM connections) should automatically open when new content is available, and perhaps even a suboption to specify if some of those tabs/panels should be allowed to take focus when new content is available in that tab.

See https://github.com/sassoftware/vscode-sas-extension/issues/651 for a related feature request.
