### ISSUE TITLE
Local/Remote IOM connection - Add Library panel support

### ISSUE THREAD

**Issue by snlwih** [sassoftware/vscode-sas-extension#680]
**Describe the solution you'd like**
When using a local/remote IOM connection, I would like to see a Libraries panel similar to what is already support for SAS Viya 4 (REST) connections. 

The libraries panel should support:
- Listing all libraries defined on the SAS server
- Expanding a library should list all tables in that library
- Dragging a table into a SAS Code editor tab should result in the string <libref>.<tablename> being added to the editor
- An option to download a table that was selected in the Libraries panel, which downloads the table content as a CSV and asks the user for a location and name to store the CSV file 

Note: Clicking on a table should open a table viewer, but that is a separate (but related) feature request, see #595.

**Environment**
Local/Remote IOM connection to SAS 9

**Comment by scottdover** [comment]
As part of library panel support, look into using eventing for managing ods html output. See comment here: https://github.com/sassoftware/vscode-sas-extension/pull/592#discussion_r1447785917

**Comment by scottdover** [comment]
> As part of library panel support, look into using eventing for managing ods html output. See comment here: [#592 (comment)](https://github.com/sassoftware/vscode-sas-extension/pull/592#discussion_r1447785917)

This will not be a part of implementing library support.
