### ISSUE TITLE
Additional Settings: Turn off hint on hover and turn off autocomplete suggestion

### ISSUE THREAD

**Issue by Criptic** [sassoftware/vscode-sas-extension#682]
**Is your feature request related to a problem? Please describe.**
The autocomplete suggestion can be wrong at times and hides crucial context.
The hover can get in the way when the cursor is moving over the screen and pop ups are coming up.

**Describe the solution you'd like**
Two checkboxes in the settings to be able to turn these two features on or off - default should be on.

**Describe alternatives you've considered**
None

**Additional context**
The hints can be turned off in SAS Studio for example.

**Environment**
Applicable to all SAS versions

**Comment by scnwwu** [comment]
There're VS Code built-in settings for them.
Editor: Quick Suggestions
Editor: Suggest On Trigger Characters
Editor › Hover: Enabled

**Comment by Criptic** [comment]
Ah good stuff - thank you.
Could this be made available to only be off for SAS or is that a big implementation?

**Comment by scnwwu** [comment]
> Could this be made available to only be off for SAS or is that a big implementation?

Yes, settings can be language specific. Please refer to
https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings
