### ISSUE TITLE
SAS 9.4 (local - COM) session startup error

### ISSUE THREAD

**Issue by jbodart-argenx** [sassoftware/vscode-sas-extension#685]
**Describe the bug**
When submitting code to a new SAS session to a SAS 9.4 (local - COM)  profile, a notification "There was an error executing the SAS Program." appears, either:
- When code is run by clicking on the running man icon, pressing "F3" or "F8" (default keyboard shortcuts): the message shows up as:
![image](https://github.com/sassoftware/vscode-sas-extension/assets/102539231/54b88f96-8d13-4205-b91f-8cc4a38771ed)
but it doesn't seem to have any consequence, other than not displaying the html output generated; the 'Output' pane shows the expected SAS log without any error or warning; after that, if some code is submitted again by clicking on the running man icon, pressing "F3" or "F8" or selecting the 'Terminal' menu item 'Run Task ...'  -> 'sas: Run sas file', the code executes normally, the html output is displayed (if any) and no other error notification occurs.
- When code is run from the 'Terminal' menu item 'Run Task ...'  -> 'sas: Run sas file', the message  appears in the 'TERMINAL' pane as:
![image](https://github.com/sassoftware/vscode-sas-extension/assets/102539231/fffedfd3-ccaf-4832-ab01-888d8f0745d7)
The expected SAS Log appears in the 'OUTPUT' pane without any error or warning; the html output generated is not displayed, and the running man icon remains disabled (it cannot be re-enabled by clicking the 'Close Current Session' button, nor by switching to another local SAS profile, only by closing and restarting VScode); when this occurs, clicking on the running man icon, pressing "F3" or "F8" has no effect (no additional code can be submitted).
![image](https://github.com/sassoftware/vscode-sas-extension/assets/102539231/5f8ea21b-bbeb-4ef8-900c-6617fb159331)
```
 *  Executing task: sas: Run sas file 

Connecting to SAS session...
SAS code running...
There was an error executing the SAS Program.
                                             See console log for more details.

Task is cancelled.


 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```
Trying to submit code again from the 'Terminal' menu item 'Run Task ...'  -> 'sas: Run sas file' results in the following message in the 'TERMINAL' pane:
![image](https://github.com/sassoftware/vscode-sas-extension/assets/102539231/6f1455a7-ebe8-455e-b7b2-f6dbd696def2)
```
*  Executing task: sas: Run sas file 

There is running task, please try again after that is complete.

 *  The terminal process failed to launch (exit code: 1). 
 *  Terminal will be reused by tasks, press any key to close it.
```

**Steps to reproduce**
Steps to reproduce the behavior: see above.

**Expected behavior**
The code is submitted without any error notification; the html output (if any) is displayed; the running man icon that was disabled during the code execution gets re-enabled.

**Screenshots**
see above

**Environment (please complete the following information):**
Client OS: Windows 10 (X64_10PRO  platform)
Extension version: [v1.5.0] - 2023-10-27
SAS version: SAS 9.4 (local - COM)  (TS1M7) 

**Additional context**
This occurs even without any customization of the vscode-sas-extension.

**Comment by ShuguangSun** [comment]
What's you SAS system? I just meet the same issue.

My SAS is installed in a windows server and has no metadata server and no workspace server and no SAS Integration Technologies, but has  SAS Integration Technologies Clients. When I login in via windows remote desktop, I can run sas code via COM in vscode. But if I sign in by SSH (vscode remote-ssh), I have the same error report as you reported.

**Comment by scnwwu** [comment]
Would you click `Help > Toggle Developer Tools` and see the error details in the console?

**Comment by ShuguangSun** [comment]
This is my console message:
```
console.ts:137 [Extension Host] ERROR: The process "22244" not found.
w @ console.ts:137

console.ts:137 [Extension Host] shellProcess stderr: at Run, <No file>: line 65

w @ console.ts:137

console.ts:137 [Extension Host] [Error: There was an error executing the SAS Program.
See console log for more details.
	at Socket.onShellStdErr (E:\Users\xxxx\UserConfig\Code\.vscode-server\extensions\sas.sas-lsp-1.5.0\client\dist\node\extension.js:247:147)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)]
notificationsAlerts.ts:42 There was an error executing the SAS Program. See console log for more details.
c @ notificationsAlerts.ts:42

console.ts:137 [Extension Host] shellProcess stderr: at ResolveSystemVars, <No file>: line 11
at <ScriptBlock>, <No file>: line 1
At line:1 char:1
+ $runner.ResolveSystemVars()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
 

w @ console.ts:137

console.ts:137 [Extension Host] shellProcess stderr: Run error
At line:70 char:7
+       throw "Run error"
+       ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Run error:String) [], RuntimeException
    + FullyQualifiedErrorId : Run error
 

w @ console.ts:137
```

**Comment by jbodart-argenx** [comment]
> What's you SAS system? I just meet the same issue.
> 
> My SAS is installed in a windows server and has no metadata server and no workspace server and no SAS Integration Technologies, but has SAS Integration Technologies Clients. When I login in via windows remote desktop, I can run sas code via COM in vscode. But if I sign in by SSH (vscode remote-ssh), I have the same error report as you reported.

I have PC SAS on a windows local laptop: no Remote Desktop, no ssh involved.

**Comment by scnwwu** [comment]
@ShuguangSun, "process not found" sounds like the powsershell process was accidentally exited. Would you kill all code-server processes on your server and try again?

**Comment by jbodart-argenx** [comment]
> Would you click `Help > Toggle Developer Tools` and see the error details in the console?

Thanks @scnwwu for the tip! 

Running with"F3" resulted in the following messages in the Developer Tools console:
![image](https://github.com/sassoftware/vscode-sas-extension/assets/102539231/2563a4bf-333a-4a10-bf5f-35a013f7923e)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/102539231/8160140b-3945-4741-bcdb-d6d1dca028a5)

Running from the 'Terminal' menu item 'Run Task ...' -> 'sas: Run sas file' resulted  in the following messages in the Developer Tools console:
![image](https://github.com/sassoftware/vscode-sas-extension/assets/102539231/1de5dc46-6296-4734-9491-6cf01e920a5b)

This showed the problem was linked to inserting option "ECHOAUTO" in my profile definition in settings.json:
```
    "SAS.connectionProfiles": {
        "activeProfile": "Local SAS 9.4",
        "profiles": {
            "Local SAS 9.4": {
                "connectionType": "com",
                "sasOptions": 
                    [
                        "ECHOAUTO",
                        "MPRINT",
                        "LS=120"
                    ],
                "host": "localhost"
            }
        }
    },
```
Removing that option fixed all the issues for submitting code by clicking on the running man icon, pressing "F3" or "F8" or selecting the 'Terminal' menu item 'Run Task ...' -> 'sas: Run sas file' 

# Suggestions to help prevent reoccurrences of the issue:
- indicate in https://github.com/sassoftware/vscode-sas-extension/blob/main/connect-and-run.md#additional-settings-in-a-profile that the Options only allowed at startup are (currently?) not supported for SAS 9.4 (local - COM)
- (not sure if this is feasible): replace the message `See console log for more details.` with the more explicit `See console log (click Help > Toggle Developer Tools) for more details.`

**Comment by ShuguangSun** [comment]
> @ShuguangSun, "process not found" sounds like the powsershell process was accidentally exited. Would you kill all code-server processes on your server and try again?

It doesn't work. As my issue is different to [jbodart-argenx](https://github.com/jbodart-argenx)'s, I will open a new issue.

**Comment by ShuguangSun** [comment]
> ```
>     "SAS.connectionProfiles": {
>         "activeProfile": "Local SAS 9.4",
>         "profiles": {
>             "Local SAS 9.4": {
>                 "connectionType": "com",
>                 "sasOptions": 
>                     [
>                         "ECHOAUTO",
>                         "MPRINT",
>                         "LS=120"
>                     ],
>                 "host": "localhost"
>             }
>         }
>     },
> ```
How about remove `mprint` from the options?

**Comment by jbodart-argenx** [comment]
Having MPRINT as an option (or not) seems to me a user preference, and as far as I can tell it is not causing any error or warning.

**Comment by ShuguangSun** [comment]
remove `ECHOAUTO` from the option as the log said: ECHOAUTO is valid only at startup...

**Comment by scnwwu** [comment]
Thank you @jbodart-argenx for the suggestions.
I added an item to the FAQ page as a first quick step.
https://github.com/sassoftware/vscode-sas-extension/wiki/FAQ#i-got-see-console-log-for-more-details-error-where-to-see-the-console-log

**Comment by scnwwu** [comment]
sasOptions doc updated via #696
See console log message updated via #782

**Comment by fslandi** [comment]
Will Startup options for SAS 9.4 (local) and (remote-IOM) be supported in the future releases?
