### ISSUE TITLE
Include Dependabot to automate dependency management

### ISSUE THREAD

**Issue by smorrisj** [sassoftware/vscode-sas-extension#69]
**Is your feature request related to a problem? Please describe.**
In the short term no, but as the project lives on dependency management will become important both from a security and a quality standpoint.

**Describe the solution you'd like**
I'd like to propose that we integrate dependabot into the repo to lessen the burden of keeping third party dependencies up to date. Ideally it would create pull requests with the changes so that they could be verified using the usual review processes. 

**Describe alternatives you've considered**
Manually checking and updating by manually making changes to the package json. That is feasible but it seems that the alternative above would automatically check and propose the updates. That would allow maintainers to focus efforts on reviewing the changes that are proposed.

**Additional context**
[Integrating dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)

**Environment**
n/a

**Comment by scottdover** [comment]
I think this is an excellent idea. It would also be  good practice to routinely have a developer run `yarn outdated` and update stale packages as needed.

**Comment by 2TomLi** [comment]
It is a great idea, I just create a PR for the dependabot.yml, please check and modify if needed.
#70

**Comment by 2TomLi** [comment]
Code merged.
