### ISSUE TITLE
Authentication Token required at each connection

### ISSUE THREAD

**Issue by alexchouchene** [sassoftware/vscode-sas-extension#698]
**Describe the bug**
Authentication Token is required at each connection in our configuration.
Our configuration uses kubeflow to launch VScode and each session is loaded in a POD.

**Steps to reproduce**

1. Go to SAS extention and click on "sign in"
 
![image](https://github.com/sassoftware/vscode-sas-extension/assets/101650470/e8b1ee53-06fe-4865-b885-dfdaa526504a)

3. Click on 'allow', then "open"
 
![image](https://github.com/sassoftware/vscode-sas-extension/assets/101650470/9fd2b986-7aef-45fc-80d6-bd53c8e2a968)

5. copy/paste the token and press enter, then we're logged in.
 
![image](https://github.com/sassoftware/vscode-sas-extension/assets/101650470/bd77144b-4dd3-4a1a-9d0b-fe2599b88ee3)

7. close the vscode tab in internet explorer and then reopen VScode: we have to begin the process from step 1.

**Expected behavior**
We'd like the authentication to be persistent, not to have to redo the authentication process after closing the kubeflow tab in the explorer.

**Environment (please complete the following information):**
Client OS: CentOS Linux release 7.9.2009 (over coderserver 4.16.1, KubeFlow 1.7)
Extensions version: v1.5.0
SAS Version: Viya LTS 2023.03 + SAS 9.04.01 M7

**Comment by scnwwu** [comment]
It's not a bug against this project. It looks like an issue against code-server that looks to be fixed at
https://github.com/coder/code-server/releases/tag/v4.17.1
If it still doesn't work, please report to code-server project, for example I saw https://github.com/coder/code-server/issues/6568.

**Comment by alexchouchene** [comment]
Thank you I'll check this!
