### ISSUE TITLE
Cannot run PROC IMPORT on remote Unix machine

### ISSUE THREAD

**Issue by rhstanton** [sassoftware/vscode-sas-extension#699]
**Describe the bug**
Running VS Code on a Mac, connecting to SAS via SSH on a remote Unix machine, I can get some code to run (so the connection works), but I get an error message if I try to run "PROC IMPORT":

NOTE: Writing HTML5 Body file: sashtml.htm
NOTE: This SAS session is using a registry in WORK.  All changes will be lost 
      at the end of this session.
ERROR: The connection to the X display server could not be made. Verify that 
       the X display name is correct, and that you have access authorization. 
       See the online Help for more information about connecting to an X 
       display server.
ERROR: Device does not support full-screen.

**Steps to reproduce**
Run the line

proc import datafile=x out=_csv dbms=csv replace; run;

**Environment (please complete the following information):**
Client OS: MacOS 12.7.2
Extension version: 1.5.0
SAS version: 9.4

**Comment by sasutils** [comment]
It looks like the remote SAS session is trying to open an X window on the remote machine.  Did you include the -noterminal option on the command you used to launch SAS?
