### ISSUE TITLE
autoExec code does not execute statements in file pointed to by filePath

### ISSUE THREAD

**Issue by snlwih** [sassoftware/vscode-sas-extension#712]
**Describe the bug**
Using autoExec tag on Viya 4 connection , with type: file and filePath: <path-to-file>, it does not execute SAS code from file. At the same time those statements show up in the SAS log for each submit, so not only on session startup. Note that I haven't tested with other connection types.

**Steps to reproduce**
1. In settings.json I have the following (excerpt):
```json
     "sasOptions": [
          "ECHOAUTO",
          "ERRORS=42",
          "ENCODING=latin1"
    ],
    "autoExec": [
          {
            "type": "line",
            "line": "libname _ALL_ list;"
          },
          {
            "type": "file",
            "filePath": "/mydir/myautoexec.sas"
          }
       ],
```
2, On first submit in the SAS editor tab I can see that the sasOptions are honoured, as I see the statements from the standard autoexec and with proc options I validated that encoding is set to latin1 instead of the default UTF-8 encoding.
3. The statements from the specified myautoec.sas file are shown in the SAS log (OUTPUT tab in Console), but they are not executed and empty lines are omitted.
5. The statement specified in the line tag is executed at session startup, and only at session startup

Contents of myautexec.sas:
```
%put Current time: %sysfunc(putn(%sysfunc(time()),time.));

proc print data=sashelp.cars(obs=10);
  title "SASHELP.CARS - proc print in autoexec file ";
run;
```

**Expected behavior**
Statements in the file pointed to by the filePath tag are executed at session startup time, and only at session startup time and not on each submit. 

**Environment (please complete the following information):**
Client OS: Windows 10 
Extension version: v1.5.0 
SAS version: Viya 2023.11

**Comment by smorrisj** [comment]
> ```json
> "filePath": "/mydir/myautoexec.sas"
> ```

Where was this directory created, on your local machine or on SAS Content?

**Comment by smorrisj** [comment]
> Statements in the file pointed to by the filePath tag are executed at session startup time, and only at session startup time and not on each submit.

Each submit does not clear out the log of the previous execution. To see if that's what you're seeing, can you try clearing the log between each submission and retrying the test? The auto exec lines are attached to the compute session on session creation so should be executed once at session startup as you say.

**Comment by snlwih** [comment]
I had cleared the log each time. Have completely rebooted my machine and now see slightly different behaviour:
1. Statements are not shown each time (so probably a PEBKEC)
2. Statements in filePath are ignored. I created a macro variable in .sas file and it does not exist in the session, so indicating that statements are ignored
3. filePath points to path mounted on Compute, and validated that it can be resolved durin the session using the following SAS code
```
data _null_; 
     infile "/mydir/myautoexec.sas"; 
     input;
     put "***INFILE***  " _INFILE_;
run;
```

**Comment by scnwwu** [comment]
Currently it only supports filePath on your local machine (where VS Code extension is running on).

**Comment by snlwih** [comment]
Then we should update the doc to explain that.

**Comment by scnwwu** [comment]
> Then we should update the doc to explain that.

Yes, could be considered together with #696

**Comment by smorrisj** [comment]
@snlwih is this a candidate to close based on changes made to address #696?

**Comment by scnwwu** [comment]
Closing. Please re-open if any additional issues.
