### ISSUE TITLE
Release 1.6.0 not working properly with version 1.6 of VSCode

### ISSUE THREAD

**Issue by snlwih** [sassoftware/vscode-sas-extension#764]
**Describe the bug**
When using Visual Studio Code 1.6 (note this is the VSCcode version not the SAS extension version), things do not seem to work properly. The SAS icon is not visible in the left-hand-side bar, existing connection profile definitions are not visible, and issuing SAS specific commands like "SAS.addProfile" return a "not found" error. Upgrading VSCode to a recent version seems to resolve the issue.

Is VSCode 1.6 supported? If not, this pre-req should show up in the doc and change log. Btw. SAS extension release 1.5.0 worked fine with VSCode 1.6.

**Steps to reproduce**

1. Install/update SAS extension
2. CTRL-SHIFT P --> SAS: Add New Connection Profile 
3. Error is displayed: "command not found"

Similar behaviour for the other SAS specific commands.

**Environment (please complete the following information):**
Client OS: [e.g. Windows 10]
Extension version: [e.g. v1.6.0]
SAS version:  n/a 

**Additional context**
Updating the version of VSCode to 1.8, like 1.85.0, seems to resolve the issue.

**Comment by snlwih** [comment]
Btw. I'm just reporting on behalf of others that have reached out to me offline, my isntallation was already on VSCode 1.85.1 so I did not experience this issue myself. Those who contacted offline will be asked to add a comment here, so they can be reached if additional follow up is needed.

**Comment by AWindisch-HUK** [comment]
Hy, received the issue also had v1.81.0 of VSCode running.

**Comment by scnwwu** [comment]
> Hy, received the issue also had v1.81.0 of VSCode running.

Hi, update to latest VS Code version should fix this issue
