### ISSUE TITLE
Cannot establish Remote-IOM connection. 

### ISSUE THREAD

**Issue by AndreyProfDev** [sassoftware/vscode-sas-extension#809]
**Describe the bug**
Cannot establish Remote-IOM connection. 

**Steps to reproduce**

1) ctrl-shift-P
2) SAS Sign-In
3) The extension wants to use SAS -> Allow
4) Error from extension: Cannot read properties of undefined (reading "account")

**Expected behavior**
Established connection with IOM server

**Screenshots**
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/963fef1d-df96-470d-a242-446f4f83491d)

**Environment (please complete the following information):**
Client OS: Windows 10
Extension version: 1.6.0
SAS version: SAS Enterprise Guide 8.3 Update 3. SAS server is SAS 9.4

**Additional context**
Visual Studio Code 1.86
SAS Integration Client seem to be installed (I can see corresponding folders in SAS Home directory)
settings.json (with XXXX instead of sensitive values)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/8217b813-970b-4162-9fef-7f2ab7588966)

**Comment by scnwwu** [comment]
@AndreyProfDev, The SAS Sign-In command is currently only used for SAS Content which is not available for SAS 9.
Please simply click the running man icon to run code for IOM connection and it will prompt you for password to establish the connection.

**Comment by AndreyProfDev** [comment]
Hi @scnwwu,

Thank you for quick reply. Unfortunately it doesn't work either.
I see the following error in extension host output

![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/9481ce26-1cc2-40f7-b4d6-e250e2f7c237)

**Comment by AndreyProfDev** [comment]
Actual content of that folder is the following:
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/3ef3faf4-36ad-46a9-9acb-7edbe070c644)

**Comment by scnwwu** [comment]
@AndreyProfDev, would you please click `Help > Toggle Developer Tools` from the top menu of VS Code and see if any other errors in the console? Thanks.

**Comment by AndreyProfDev** [comment]
@scnwwu,

Sure, please see below
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/585329ab-6236-4ed1-9703-9889c1672752)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/e47b4277-dc55-44e0-a8bd-0f24620d4e5a)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/d2777fb8-1db5-414d-ae71-d3b5e516c511)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/04429220-aeef-435b-9482-1cfedd051b74)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/48d15e15-937c-442f-9217-16c989bd432e)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/2fa58e09-a35d-4cde-a92c-cbc6cf086f7e)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/33dbe4ac-c46d-4e52-a234-25cd0acba394)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/14861649/f33b02fa-5dc4-4acc-bd41-460ddbdbe659)

**Comment by scnwwu** [comment]
OK. Looking at the first message in your snapshot, the PowerShell process is under [ConstrainedLanguage](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_modes?view=powershell-7.4#constrainedlanguage-mode) mode which doesn't provide enough permission for the extension to communicate with SAS Integration Technologies Client.
I'm not an expert on this but it looks like by your system policy.

**Comment by AndreyProfDev** [comment]
@scnwwu,

Thank you
You are right. I've checked in VSCode terminal and it was run under ConstrainedLanguage Mode

I've re-started VSCode with --no-sandbox option (from admin powershell) and it worked.
I can now execute .sas files. .sasnb notebooks also work. 
It is amazing. Thank you so much

BTW in VSCode terminal I can also see now that powershell operates in Full Language mode

**Comment by scnwwu** [comment]
> @scnwwu,
> 
> Just a quick question Is it possible to convert .sasnb file to .sas script?

Currently no such feature. Please file a feature request if you'd like.
Currently you can convert .sasnb to a SAS Studio flow.

**Comment by scnwwu** [comment]
Glad it works. Closing.
