### ISSUE TITLE
Add New File... -> SAS file

### ISSUE THREAD

**Issue by scnjdl** [sassoftware/vscode-sas-extension#811]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a *.sas to the text part of new file similar to how Python is there and SAS notebook has been added? Yes, I can add a text file and change to sas, but this would be more convenient.  And I do not want to use a notebook.

**Describe the solution you'd like**
add a new menu item to create sas file.

**Describe alternatives you've considered**

**Additional context**

**Environment**
SAS version

**Comment by snlwih** [comment]
@scnjdl , has this been released? If so, could you move it into the appropriate milestone?

**Comment by scnjdl** [comment]
@snlwih , sorry for missing this comment.
The milestone is on PRs, not on issues. The PR related with this is #812.

**Comment by snlwih** [comment]
@scnjdl , got it. Still something was not right with it as it was still listed in  milestone Backlog Candidate. Have removed that milestone now. (spring cleaning :smiley:)
![image](https://github.com/sassoftware/vscode-sas-extension/assets/35299890/d8356b48-5871-4e5e-b356-e467d6d847a5)
