### ISSUE TITLE
Output not returns using SAS 9.4 IOM connection

### ISSUE THREAD

**Issue by sasutils** [sassoftware/vscode-sas-extension#827]
When I use VSCode to connect to a SAS Workspace Server using the SAS 9.4 IOM connection type I do not get any output.

Any code I submit that tries to generate output VSCode says there were errors.  But the SAS log lines do not show any errors.

It the htm file that the HTML5 ODS destination that VSCode created for me exists and appears to be valid.  But it does not get displayed.

Here is code I ran that shows that the htm file was created.

proc print data=sashelp.class;
run;
data _null_;
    infile "%sysfunc(pathname(work))/*.htm" filename=fname;
    input;
    if fname ne lag(fname) then do; fileno+1; lineno=0; end;
    lineno+1;
    if lineno<10 then put lineno 1. +1 _infile_;
run;

I also noticed that it is putting metadata in the HTML file saying the file is UTF-8, but my SAS session is using LATIN1 encoding.

**Comment by scnwwu** [comment]
Closing per above comment.
