### ISSUE TITLE
Add matrix documenting capabilities supported for each server connection type

### ISSUE THREAD

**Issue by snlwih** [sassoftware/vscode-sas-extension#841]
**Is your feature request related to a problem? Please describe.**
We have a number of capabilities that are not available across all connection types and this is not always clear from the documentation. 

**Describe the solution you'd like**
A matrix listing all the capabilities across one dimension and the connection types across the other dimension with a checkmark in the cell if that capability is supported for the specific connection type. 

**Describe alternatives you've considered**
For connection types we have information about what options (autoexec statement, configuration options) are supported for ech connection type. (see https://github.com/sassoftware/vscode-sas-extension/blob/main/connect-and-run.md#additional-settings-in-a-profile). We could add info there about whether capabilities like Table Viewer, SAS log color-coding, ... are supported. But it is not easy to find and many users would not look there.

A dedicated documentation file containing a matrix of features supported for each connection type is much easier to read and understand. That doc could then have links to dedicated doc with more details.

**Comment by scnwwu** [comment]
I just took a try. Please see
https://scnwwu.github.io/vscode-sas-extension/matrix

**Comment by jennifert-sas** [comment]
@scnwwu That looks very nice! I made a draft table, as well, with links to more details. Can we include links once we have settled on all the content that needs to be included? I'll email you a link to my document.
cc: @clangsmith @snlwih

**Comment by clangsmith** [comment]
@scnwwu, I love the decision tree diagram! @jennifert-sas, I reviewed your draft doc and added some comments. Thank you both.

**Comment by snlwih** [comment]
@scnwwu , can the columns showing the checkmarks be centered? Have added comments for the tree diagram in #865.
