### ISSUE TITLE
Using SSH connection returns "Command not found" in SAS log

### ISSUE THREAD

**Issue by madrodger** [sassoftware/vscode-sas-extension#863]
Hi, I'm trying to submit SAS code to a RedHat Linus system using the SSH method. I followed the installation instructions, https://github.com/sassoftware/vscode-sas-extension/blob/HEAD/connect-and-run.md#add-new-sas-94-remote---ssh-profile, and it seems to communicate with the server but I get this in the SAS log when I submit code using the Running Man, 
[rodger@pandora ~]$
_JAVA_OPTIONS="-Djava.awt.headless=true" /net/sas94linuxM6/S ASFoundation/9.4/bin/sas_u8 -nodms -terminal -nosyntaxcheck
_JAVA_OPTIONS=-Djava.awt.headless=true: Command not found.

Not sure why it is sending the Java options. Any ideas?

Here is my settings.json file:

{
    "security.allowedUNCHosts": [
        "pandora"
    ],
    "workbench.colorCustomizations": {

    },
    "workbench.preferredHighContrastColorTheme": "Quiet Light",
    "workbench.colorTheme": "SAS Light",
    "SAS.connectionProfiles": {
    
        "activeProfile": "pandora",
        "profiles": {
            "pandora": {
                "connectionType": "ssh",
                "host": "pandora.rand.org",
                "saspath": "/net/sas94linuxM6/SASFoundation/9.4/bin/sas_u8",
                "username": "rodger",
                "port": 22
            }
        }
    },
    "sasjs-for-vscode.isLocal": false
}

Thanks, 

     Rodger

**Comment by scnwwu** [comment]
looks similar to #1005
Are you using csh too?

**Comment by chunky** [comment]
@scnwwu I actually work with @madrodger , you'll see the server mentioned in my example profile in #1005 is "pandora", just like the one in his. Not an accident :-)

[I hadn't realised that @madrodger  had already put in this ticket, else I'd have posted my recommended fix in this thread. My apologies]

**Comment by scnwwu** [comment]
@chunky thank you for figuring out the problem!
