### ISSUE TITLE
Publish documentation using GitHub.io pages

### ISSUE THREAD

**Issue by snlwih** [sassoftware/vscode-sas-extension#865]
**Is your feature request related to a problem? Please describe.**
Now that the SAS extension for Visual Studio Code has a lot of features and documentation, it becomes more difficult to quickly find information. Readme pages become very long with a long table of contents at the top, and the documentation pages for individual features also become large and difficult to read and navigate. 

**Describe the solution you'd like**
Documentation pages with a table of contents displayed in a panel, separated from the explanations themselves. That table of contents should allow for expanding chapters/sections into subsections, and when clicking on a section the actual section content would show next to the ToC. Search capabilities should also be provided. 
It should be easy for contributors to provide new capabilities including related doc that can (automatically) be added to those GitHub pages

Examples used by other SAS projects on GitHub: 
- [SASPy documentation pages](https://sassoftware.github.io/saspy/) 
- [sasctl documentation pages](https://sassoftware.github.io/python-sasctl/). 
 
Both use so called [GitHub pages](https://docs.github.com/en/pages).

The GitHub repo itself would then show a link to these doc pages at the top right of the main repo page.

**Comment by scnwwu** [comment]
SASPy and sasctl are built with [Sphinx](https://www.sphinx-doc.org/), which is good for Python. There's no Python depdendency in this project. [Docusaurus](https://docusaurus.io/) looks a good option for Typescript and React world.
I deployed one to my forked repo with current README and connect-and-run markdown file, see
https://scnwwu.github.io/vscode-sas-extension/
Developers continue to author markdown in main branch. It will automatically build to GitHub Pages, with auto navigation, light/dark mode, search support.
We can further re-organize the pages, improve the content as appropriate. For example splitting to shorter pages, providing quick start section, etc.

**Comment by jennifert-sas** [comment]
@scnwwu @snlwih  I think this looks nice and much easier to navigate.

**Comment by snlwih** [comment]
Agreed. Would it be possible to have the columns with markers centered?

**Comment by scnwwu** [comment]
> Info is very good, but have some suggestions for changing the way things look:
> 
> * Would it be possible to center the columns in the matrix that contain markers?
> * The descision tree at the top is informative, but takes up far too much space. The user's primary interest is the matrix itself. When you open the page currently you don't even see the matrix, as the graph takes up the whole screen (1900x1200 Full HD with standard font size). You have to scroll down to even see a part of the matrix. I would say that the decision tree info could also be captured in a more ASCII tree that has a horizontal direction and then not take up more than 10 lines or so. Quickly did this in a ascii text editor. I'm sure there are slighly better ways to capture this in ASCII, but hope you get the point. If markdown has a way to capture this more graphically without taking up more space, then of course I'm open to such an approach as well.
> 
> ```
>               +-->  Viya  -->  SAS Viya
>               !
> SAS Version --+
>               !
>               !                                     +-->  No   -->  SAS 9.4 (remote -SSH)
>               !                                     !
>               +-->  9.4   -->  VSCode on Windows  --+                                       +-->  Yes --> SAS 9.4 (local)
>                                                     !                                       !
>                                                     +-->  Yes  -->  Connection to local?  --+
>                                                                                             !
>                                                                                             +-->  No  --> SAS 9.4 (remote - IOM)
> ```

Centered the check marks and made the tree horizontal.
