### ISSUE TITLE
Fileref OUTFILE should be allowed for COM/IOM

### ISSUE THREAD

**Issue by scnwwu** [sassoftware/vscode-sas-extension#868]
### Discussed in https://github.com/sassoftware/vscode-sas-extension/discussions/858

Run below code against COM/IOM, error occurs.
```
filename outfile '/path';
proc print data=sashelp.class;
run;
```

**Comment by sasutils** [comment]
Any progress on this?  It should be simple to at least change the fileref that is hardcoded in the extension from OUTFILE to some other name that is less likely to be used by the users SAS program.
