### ISSUE TITLE
Create files in SAS Content with proper content-type

### ISSUE THREAD

**Issue by brunomueller** [sassoftware/vscode-sas-extension#878]
**Is your feature request related to a problem? Please describe.**
For a SAS Viya connection we can create files in SAS Content. However they are not created with the proper content-type.
Example:
Create a .html file in SAS Content works just fine, but will be created as 
{
  "creationTimeStamp": "2024-03-05T15:37:40.994Z",
  "modifiedTimeStamp": "2024-03-05T15:38:20.809Z",
  "createdBy": "...",
  "modifiedBy": "...",
  "id": "e55727e5-f7c5-40fc-b585-abe40bf34af9",
  "properties": {  },
  "contentDisposition": "filename*=UTF-8''simple.html",
  **"contentType": "text/plain",**
  "encoding": "UTF-8",

This means the file can not be used as a source for lets say a WebContent or DataDrivenObject in Visual Analytics. See this https://communities.sas.com/t5/SAS-Communities-Library/Deploy-DDC-Implementation-Files-in-SAS-Content-Server-via-SAS/ta-p/825559 for more details on storing .js, .css, .html in SAS Content

**Describe the solution you'd like**
Files create in SAS Content should have the proper content-type, so that they can be accessed using the SASJobExecution application using "/SASJobExecution/?_file=</full_path/file_name>" as described in the communities article above. Maybe using https://server/files/files/.../content will work as well.

**Additional context**
Since VSCode has good support to create .html, .js, .css files it would be great if files with these extensions are created appropriately in SAS Content.

**Environment**
Extension: 1.7.1, SAS Viya 2024.01

**Comment by scottdover** [comment]
https://github.com/broofa/mime looks to have what we need to implement this. I'll take a look at this one soon :)

**Comment by scottdover** [comment]
Thanks for bringing this one to our attention, @brunomueller. I believe we've found a solution in the linked pull request. This should be resolved in the 1.9.0. release :)

**Comment by scottdover** [comment]
Interesting. Both things go through the same code path as far as I know. I'll take another look. Thanks for catching that :)

**Comment by scottdover** [comment]
Hey @bruno-mueller-sas. I took a look into this. I'm wondering if I'm doing something differently than you. Here's what steps I'm taking:
 - Click the sas icon in the left activity bar, sign in
 - Create a new folder under my folder
 - Create a new file using the context menu (right click)
 - Name the file test.html
 - Get the file uri. Visit `<domain>/files/files/<uuid>`
 - Make sure the content type is `text/html`

Ah, I think I've found the issue
 - I edited test.html and saved it
 - After the file is saved, the content type is updated to `text/plain`

**Comment by scottdover** [comment]
Hey @bruno-mueller-sas . I have a partial fix for this, and will wrap it up mid next-week to be included in the 1.10.0 release. Question for you. If I rename a file from a .html to .txt (or other extension), the expectation is that the content type will be updated as well, right?

**Comment by bruno-mueller-sas** [comment]
@scottdover Thanks. I do think it does make sense to change the content type when renaming a file.

**Comment by scottdover** [comment]
Hey @bruno-mueller-sas. I was looking at implementing switching content types when renaming files. Currently, there's no clear approach to do that with the endpoints we're using. Also, it looks like both studio and sas drive do not update content types when renaming files. So, I'll likely not include that in this issue.

**Comment by bruno-mueller-sas** [comment]
Thanks for the update, being consistent makes sense.
