### ISSUE TITLE
No HTML5 Listing Output Returned and Errors Encountered With IOM Connection

### ISSUE THREAD

**Issue by tedconway** [sassoftware/vscode-sas-extension#898]
Hi, I'm using the SAS VS Code extension (1.7.2) with Visual Code (1.87.2) to connect to a remote Linux SAS server (SAS 9.4M6) using an IOM connection (phew!).

However, with HTML5 output unchecked, when I submit SAS code from a simple *.sas file, I can see log output (e.g., from PROC SETINIT) but no list output (e.g., from PROC PRINT or SQL) even though the log shows the procedures ran fine.

With HTML5 output checked, I see no log/list output when code is submitted from a *.sas file.

And if I submit simple code (proc setinit; run;) with HTML5 output enabled from a SAS Notebook, not only is there no output, but the following error message is displayed (saw something similar in another post, but no solution was identified in post):
_____
 
Error: There was an error executing the SAS Program. See [console log](command:workbench.action.toggleDevTools) for more details.
at Hx.onShellStdErr (c:\Users\myIDhere\.vscode\extensions\sas.sas-lsp-1.7.1\client\dist\node\extension.js:264:155)
at Socket.emit (node:events:514:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at Socket.push (node:internal/streams/readable:234:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
_____

Console output suggests HTML output in temporary work directory could not be found. If I specify an ODS HTML5 output file name with a path to a permanent directory, the output file does get created, but VS Code still can't find it and retrieve it.

So, any thoughts/suggestions of what might be going wrong and/or what I'm missing?

Very neat extension, hope to get it running soon!

Thanks! 

tc
 
Btw, below is what profile looks like as well as successful SAS Integration Technologies test dropdown settings:
_____

"sas9IOM": {
"username": "my ID here",
"host": "my.server.com",
"port": 8591,
"sasOptions": [],
"connectionType": "iom"
},
_____

SAS Integration Technologies Configuration Wizard drop down options:

SAS Workspace Server
IOM Bridge
Credentials
SASProprietary
_____

I've also tried disabling all other VS Code extension and change the JSON file to add SAS options (NONEWS + ECHOAUTO + PAGESIZE=MAX) and to specify an appserver ("SASApp), but these changes made no difference.

**Comment by tedconway** [comment]
Thought I'd mention the code is being submitted to a SAS GRID, just in case there are any special considerations for this environment.

**Comment by tedconway** [comment]
So, this unfortunately the SAS GRID appears to be the problem. Guess I'll cool my jets until an enhancement can be made (or try to dig up another non-GRID SAS server!).

Discover the Possibilities: SAS® Visual Studio Code Extension Q&A, Slides, and On-Demand Recording 
https://communities.sas.com/t5/Ask-the-Expert/Discover-the-Possibilities-SAS-Visual-Studio-Code-Extension-Q/ta-p/918293 
Can I use this with SAS GRID? 
**SAS Grid does not support IOM or SSH based SAS session creation.** You can open a feature request on GitHub for this, to get it assessed further.

**Comment by clangsmith** [comment]
Correct. Traditional Grid setup is not currently supported with the SAS Extension for VS Code, thus closing this issue. However, Grid-launched/balanced workspace servers are supported with the SAS Extension for VS Code. See my comment here for more details:
https://github.com/sassoftware/vscode-sas-extension/issues/901#issuecomment-2080323043
