### ISSUE TITLE
For users of the viya-for-learners , how can they obtain an  authorization code ?

### ISSUE THREAD

**Issue by dfmjndm** [sassoftware/vscode-sas-extension#899]
When I tried to log in using the plugin, it redirected me to the browser and then it prompted me that "The application is not authorized to use SAS Logon Manager“. Then I returned to vscode, and the interface displayed that an authorization code is required. 
I contacted the IT department of my education email, but they also don't know. Can you provide more detailed instructions?

**Comment by scnwwu** [comment]
What is your Viya version?
Please refer to the description around "Client ID"
https://github.com/sassoftware/vscode-sas-extension/blob/main/connect-and-run.md#add-new-sas-viya-profile

**Comment by dfmjndm** [comment]
> What is your Viya version?你的薇娅是什么版本？ Please refer to the description around "Client ID" 请参阅“客户端ID”周围的描述 https://github.com/sassoftware/vscode-sas-extension/blob/main/connect-and-run.md#add-new-sas-viya-profile

My Viya version is V.03.05. I have already read the link above, and the production date of my Viya is before 2022 (but strangely, I registered Viya recently).

**Comment by scnwwu** [comment]
> My Viya version is V.03.05. I have already read the link above, and the production date of my Viya is before 2022 (but strangely, I registered Viya recently).

so, you'll have to ask your SAS administrator to register a Client ID for you.

**Comment by dfmjndm** [comment]
That is the point. For Viya for Learner, When I consult the IT department of my organization , no one knows what the SAS administrator account is.

**Comment by snlwih** [comment]
@dfmjndm, any updates? Did your SAS Admin register a **_client ID_** and **_client secret_** as explained in the [SAS Communities article](https://blogs.sas.com/content/sgf/2023/02/07/authentication-to-sas-viya/) and then specify these in your connection profile? Did it work?

**Comment by dfmjndm** [comment]
I have given up on the educational version of Viya for Learner because it is free and does not have a client ID
