### ISSUE TITLE
Access to Tables/Views/Data/Libraries

### ISSUE THREAD

**Issue by engmtcdrm** [sassoftware/vscode-sas-extension#9]
It would be awesome if we could get support for accessing libraries and dat in VSC. Only being able to see data via proc print is not viable in a development environment.

**Comment by mail2fei** [comment]
This request is already in our feature backlog.

**Comment by scottdover** [comment]
This is a duplicate of https://github.com/sassoftware/vscode-sas-extension/issues/129
