### ISSUE TITLE
Environment variable SAS_EXECFILEPATH now seems to be defined but empty

### ISSUE THREAD

**Issue by jbodart-argenx** [sassoftware/vscode-sas-extension#915]
**Describe the bug**
Environment variable SAS_EXECFILEPATH, when code is submitted from enhanced editor in SAS 9.4 Display Manager environment (aka PC SAS) contains the path and filename of the program being submitted.
This environment variable used not to be set when running SAS code in SAS VScode extension using a local session, so macro-variable &_SASPROGRAMFILE was added to provide similar functionality.

My SAS programs check for &_SASPROGRAMFILE and use that information when environment variable SAS_EXECFILEPATH does not exist. Suddenly this stopped working, as environment variable SAS_EXECFILEPATH now appears to exist when running SAS code in SAS VScode extension local session, but it is empty.

**Steps to reproduce**

1. submit code:
```
%macro test();
   %if %sysfunc(sysexist(SAS_EXECFILEPATH)) %then %do;
      %if %length(%sysget(SAS_EXECFILEPATH))=0 %then %put Environment variable SAS_EXECFILEPATH exists but is empty.;
   %end;
%mend test;
%test();
```

**Expected behavior**
I wish to understand why this happened, as I could not find the string SAS_EXECFILEPATH  in the SAS VSCode extension codebase, nor found it mentioned in the Change Log.
If somehow the extension was made to define that environment variable, perhaps it could be set to the path of the SAS program being executed to match SAS 9.4 Display Manager (PC SAS) behavior.
Alternatively it could be useful to warn users of this change - perhaps described as a breaking change in the Change Log.

**Environment (please complete the following information):**
Client OS: Windows 10
Extension version: v1.8.0
SAS version: Local SAS 9.4 TS1M8

**Comment by scnwwu** [comment]
I run your code with a local 94 profile and didn't see any output, that is, SAS_EXECFILEPATH doesn't exist.
As you said SAS_EXECFILEPATH doesn't appear in the codebase. It looks like specific to your environment.
