### ISSUE TITLE
Can't connect to sas9.4 local

### ISSUE THREAD

**Issue by Super-wyc** [sassoftware/vscode-sas-extension#927]
**Describe the bug**
when i set profile in vscode, give me a error "Cannot read properties of undefined (reading 'account')"
![image](https://github.com/sassoftware/vscode-sas-extension/assets/120614710/a618cd2b-4a6c-4743-89a3-6fb90e9309ec)

**Steps to reproduce**
1. ctrl-shift-P
2. SAS Sign-In
3. The extension wants to use SAS -> Allow
4. Error from extension: Cannot read properties of undefined (reading "account")

**Expected behavior**
connect to local sas

**Environment (please complete the following information):**
Client OS: Windows 11
Extension version: v1.8.0
SAS version: SAS 9.4

**Additional context**
the extension settings like this,
    "SAS.connectionProfiles": {
    
        "activeProfile": "sas",
        "profiles": {
            "sas": {
                "connectionType": "com",
                "sasOptions": [],
                "host": "localhost"
            }
        }
    }

**Comment by Super-wyc** [comment]
![image](https://github.com/sassoftware/vscode-sas-extension/assets/120614710/86a2d4e6-bd53-49da-bee2-3f8563d86712)
The details of error above.
And i can't use the extension's some features in vscode.

**Comment by kgatman** [comment]
I'll be on the lookout for any solution regarding this. I have SAS 9.4 installed

**Comment by scnwwu** [comment]
The error in your snapshot looks same to the first snapshot in https://github.com/sassoftware/vscode-sas-extension/issues/809. As my comment in https://github.com/sassoftware/vscode-sas-extension/issues/809, it is due to Sign In command is not for SAS 9. Please click the running person icon to run code and post the snapshot for any error for it. Thanks.

**Comment by Super-wyc** [comment]
> The error in your snapshot looks same to the first snapshot in #809. As my comment in #809, it is due to Sign In command is not for SAS 9. Please click the running person icon to run code and post the snapshot for any error for it. Thanks.

Actually, no running person icon in my vscode, I can use "F3" to run .sas. I can use vscode to run .sas, no errors were reported when I ran sas, but the sas log only can be seen at output, some features of this extension are not reflected elsewhere.  I have seen the #809, but the solution was not efficient for me.
![image](https://github.com/sassoftware/vscode-sas-extension/assets/120614710/ea140be2-48c2-4c1a-93a8-e6f57475c29a)
I seem to be able to connect to sas, although the error got when I created the profile. But as i said before, I seem can't use some features of the extension.
![image](https://github.com/sassoftware/vscode-sas-extension/assets/120614710/e26c9235-be87-469d-943d-f1c2711e4c29)

**Comment by scnwwu** [comment]
Sounds like it works well. Some features are only available for Viya right now. Please see feature requests like #680, #889
Please let me know if any specific thing you think should work on SAS 9 right now but not on your device. Thanks.

**Comment by dfmjndm** [comment]
So content navigation cannot be used in the local version of SAS 9.4 and can only be used in SAS via? I don't know why # 680 has been closed, even though this issue hasn't been resolved yet.

**Comment by scnwwu** [comment]
> So content navigation cannot be used in the local version of SAS 9.4 and can only be used in SAS viya? I don't know why #680 has been closed, even though this issue hasn't been resolved yet.

As you can see in #680, it's resolved by #880 and will be available in v1.9.0
