### ISSUE TITLE
Character variable length is wrong

### ISSUE THREAD

**Issue by EHBatSAS** [sassoftware/vscode-sas-extension#928]
**Describe the bug**
The request was:

/* Craete a data set with a character variable that holds 10 characters.  */

This generated the code:
`data sample_data;
   length character_variable $10;
run;`

While this is correct for a SAS session running with a single-byte session encoding, such as LATIN1, the response is incorrect for the default Viya session encoding, UTF-8. Character variables must have enough space for multi-byte UTF-8 character data. 

Customers should be given a way to specify a multiplier value that will calculate the size of character variables on their behalf. Otherwise, the generated code is going to cause truncation and other failures for those who have multi-byte characters in their data.

An example of such a multiplier is the multiplier used by the CVP LIBNAME engine to expand the length of character variables in an existing SAS table.
https://go.documentation.sas.com/doc/en/pgmsascdc/v_048/engsas7bdat/p0pzd23juq7zj8n10ahjcc5eitro.htm 

**Steps to reproduce**

1. Create a new SAS Connection Profile to a SAS Viya server.
2. Create a new .sas file.
3. Add the comment /* Create a data set with a variable that holds 10 characters */ and generate code.

**Expected behavior**
The variable is defined as $10. 

**Screenshots**

**Environment (please complete the following information):**
Any SAS session with ENCODING=UTF-8

**Additional context**

**Comment by scnwwu** [comment]
@EHBatSAS, sounds like you're reporting issue to copilot. Please report to the dedicated project. https://github.com/sassoftware/sas-copilot
