### ISSUE TITLE
Enhance SAS authentication

### ISSUE THREAD

**Issue by scottdover** [sassoftware/vscode-sas-extension#94]
**Is your feature request related to a problem? Please describe.**
At the moment, if a user closes & opens a vscode window, the user has to log back in. This leads to more redirection than is necessary, and could be frustrating for the user.

**Describe the solution you'd like**
My hope is that we can use `AuthenticationProvider` and cache the results so that a new window can use the cached access / refresh token to establish a session

**Comment by clangsmith** [comment]
May be worth looking into this [SAS Authentication Library for the Browser](https://github.com/sassoftware/sas-viya-sdk-js/tree/main/sdk/sas-auth-browser) and/or discussing with @brmorr to see if anything we could learn from or re-use. It looks like that is the approach they are recommending for consumers of the VA SDK.

**Comment by brmorr** [comment]
Currently sas-auth-browser supports cookie based auth and will soon also support oAuth with PKCE.  But, as indicated by the package name, is really meant specifically for browser based auth.  But it has been discussed that it may also be desired to have a similar sas-auth-node package.  I am not familiar with how the auth currently works for the SAS extension, or more generally how other VS Code extensions handle auth.  But it seems like this would probably be a node thing, not a browser thing.
