### ISSUE TITLE
identifier from marketplace doesn't seems to work

### ISSUE THREAD

**Issue by YvesMarieLeDrogoff** [sassoftware/vscode-sas-extension#953]
Dear team,
We are using VS Code from a Posit Workbench Server and follow this guidance: https://docs.posit.co/ide/server-pro/vscode_sessions/vs_code_sessions.html

So far we succeed to install all the required extensions but for the SAS one, the identifier doesn't seems to be recognized.

I am executing the following commands:
![sas ext install fail](https://github.com/sassoftware/vscode-sas-extension/assets/72564388/b08a57a4-8afb-4a2a-9f72-3d012cd45720)
![sas market](https://github.com/sassoftware/vscode-sas-extension/assets/72564388/e5bdfe5e-5b40-4a1a-a521-468b9f644b93)

I wonder if the identifier is correct as we are failing only on this extension. Thanks in advance for your help.

Kind regards,
Yves-Marie

**Comment by scnwwu** [comment]
The identifier **is** correct.
Posit Workbench is using [code-server](https://github.com/coder/code-server), which is NOT Microsoft's VS Code. Please refer to https://coder.com/docs/code-server/latest/FAQ#why-cant-code-server-use-microsofts-extension-marketplace
You'll need to download VSIX file from marketplace and follow the "Alternatively, paths to local extension files (.vsix)" part of the doc
https://docs.posit.co/ide/server-pro/vscode_sessions/installation.html#pre-installing-vs-code-extensions

**Comment by YvesMarieLeDrogoff** [comment]
Thanks a lot !
