### ISSUE TITLE
Can not install Extension pack from marketplace or extensions in VS

### ISSUE THREAD

**Issue by Timbedsted1234** [sassoftware/vscode-sas-extension#960]
**Describe the bug**
Hello I have tried to go to market place andinstall .Nothing happens.

When I then go to my VS and search extensions I ccan not find the extension package

**Steps to reproduce**
Step 1:
https://marketplace.visualstudio.com/items?itemName=SAS.sas-lsp

Step 2:
My version
![image](https://github.com/sassoftware/vscode-sas-extension/assets/41056573/fe75ad5a-bb46-448c-945a-d112c4e402b1)

Can not find SAS extension in extensions 
![image](https://github.com/sassoftware/vscode-sas-extension/assets/41056573/bcb328a7-6ebb-4a22-a8b7-879735ebe2ea)

**Expected behavior**
I would expect to be able to click install button and see an installation begin.

**Screenshots**
I have added above

**Environment (please complete the following information):**
Client OS: [Win10 
Extension version: 1.8.0
SAS version: SAS 9.4m6

**Additional context**

**Comment by scnwwu** [comment]
This extension is for [VS Code](https://code.visualstudio.com/), NOT Visual Studio. They're different product.
