### ISSUE TITLE
Unable to complete IOM connection

### ISSUE THREAD

**Issue by sasutils** [sassoftware/vscode-sas-extension#964]
**Describe the bug**
I cannot complete connection to SAS 9.4 on Unix from VSCODE on PC.  It was working before (2 to 3 weeks ago) and now it connects and I can see start of SAS log in VSCODE. but then it just waits (for what?) and never seems to actually submit my SAS code.  I can submit to "local" connection to Windows SAS 9.4 session.  Instead it just has message window saying connection to SAS session.

**Steps to reproduce**
Open or create SAS program.  For my example I just use "proc setinit;run;" as the code. Select SAS connection defined using IOM connection.  Submit code to run.

**Expected behavior**
SAS log should show results of running the code.

**Screenshots**

**Environment (please complete the following information):**
VSCODE Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

SAS version: 9.4 (TS1M7 MBCS3170)
Host version: Linux LIN X64 3.10.0-1160.105.1.el7.x86_64 #1 SMP Mon Nov 6 06:58:51 EST 2023 x86_64 Red Hat Enterprise Linux Server release 7.9 
      (Maipo) 

**Additional context**
Worked before.  Works when connecting to LOCAL.  Now cannot get past the line in the SAS log of the code generated by the VSCode extension:  

%let workDir = %sysfunc(pathname(work));

**Comment by scnwwu** [comment]
I didn't reproduce.
@sasutils, are you using same version of the extension when it worked? If so, what have changed? You mentioned working directory. Did your default working directory changed?

**Comment by sasutils** [comment]
I am not sure if VSCODE (or SAS extension) have changed as they update themselves.  I also might have had some updates pushed to my Windows machine.    Not sure if working directory has changed, as that is controlled by the SAS admins, but they have not made any announced changes to the environment and the paths generated look the same.  

But it is strange that the connection to SAS is actually being made fine as I can see the top of the SAS log fine.  But it is then getting hung up somehow.  The last line that appears in the SAS log I can see on my PC is from code submitted by the VSCODE extension.  I see a similar line when I connect to LOCAL copy of SAS.

I do not know how to revert to an older version of the SAS extension.  Are there instructions for doing that somewhere?

**Comment by scnwwu** [comment]
> I do not know how to revert to an older version of the SAS extension. Are there instructions for doing that somewhere?

You can go to the Extenions panel, select the Manage gear button at the right of an extension entry and then select "Install Another Version..." from the menu.
https://code.visualstudio.com/assets/docs/editor/extension-marketplace/uninstall-extension.png

You may want to disable auto-update when testing an old version to prevent it from auto-updating to a newer version.
https://code.visualstudio.com/docs/editor/extension-marketplace#_extension-autoupdate

**Comment by scnwwu** [comment]
BTW., is there any error/warnings from the VS Code console?

**Comment by sasutils** [comment]
There does not appear to be any VSCODE logging.  Perhaps I need to activate it.

But I did find the change to our environment.  We have installed SAS session monitoring since I last tried to use it.  Perhaps you can test if that breaks the VSCODE SAS extension?

**Comment by jinmei98** [comment]
Same issue and unable to connect SAS 9.4M7 from Linux using VS Code.   Here is partial error from console:
$logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:1623
S @ workbench.desktop.main.js:sourcemap:1623
Q @ workbench.desktop.main.js:sourcemap:1623
M @ workbench.desktop.main.js:sourcemap:1623
L @ workbench.desktop.main.js:sourcemap:1623
(anonymous) @ workbench.desktop.main.js:sourcemap:1623
y @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:628
q.onmessage @ workbench.desktop.main.js:sourcemap:1641
workbench.desktop.main.js:sourcemap:152 [Extension Host] stack trace: TypeError: Class constructor gi cannot be invoked without 'new'
	at y (c:\Users\*******\.vscode\extensions\kiteco.kite-0.147.0\dist\kite-extension.js:2:330718)
	at Object.setStatusBarLabel (c:\Users\g546363\.vscode\extensions\kiteco.kite-0.147.0\dist\kite-extension.js:2:347850)
	at c:\Users\******\.vscode\extensions\kiteco.kite-0.147.0\dist\kite-extension.js:2:348765
w @ workbench.desktop.main.js:sourcemap:152
$logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:1623
S @ workbench.desktop.main.js:sourcemap:1623
Q @ workbench.desktop.main.js:sourcemap:1623
M @ workbench.desktop.main.js:sourcemap:1623
L @ workbench.desktop.main.js:sourcemap:1623
(anonymous) @ workbench.desktop.main.js:sourcemap:1623
y @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:628
q.onmessage @ workbench.desktop.main.js:sourcemap:1641
workbench.desktop.main.js:sourcemap:2008 [kiteco.kite]Class constructor gi cannot be invoked without 'new'
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:2008
S @ workbench.desktop.main.js:sourcemap:1623
Q @ workbench.desktop.main.js:sourcemap:1623
M @ workbench.desktop.main.js:sourcemap:1623
L @ workbench.desktop.main.js:sourcemap:1623
(anonymous) @ workbench.desktop.main.js:sourcemap:1623
y @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:628
q.onmessage @ workbench.desktop.main.js:sourcemap:1641
workbench.desktop.main.js:sourcemap:2008 TypeError: Class constructor gi cannot be invoked without 'new'
	at y (c:\Users\******\.vscode\extensions\kiteco.kite-0.147.0\dist\kite-extension.js:2:330718)
	at Object.setStatusBarLabel (c:\Users\*******\.vscode\extensions\kiteco.kite-0.147.0\dist\kite-extension.js:2:347850)
	at c:\Users\******\.vscode\extensions\kiteco.kite-0.147.0\dist\kite-extension.js:2:348765
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:2008
S @ workbench.desktop.main.js:sourcemap:1623
Q @ workbench.desktop.main.js:sourcemap:1623
M @ workbench.desktop.main.js:sourcemap:1623
L @ workbench.desktop.main.js:sourcemap:1623
(anonymous) @ workbench.desktop.main.js:sourcemap:1623
y @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:628

**Comment by pittonla** [comment]
Same issue and unable to connect SAS 9.4M7 from Linux using VS Code for SAS 9.4 remote IOM
SAS extension: 1.9.0
Works when connecting to LOCAL. Now cannot get past the line in the SAS log of the code generated by the VSCode extension:
%let workDir = %sysfunc(pathname(work));
