### ISSUE TITLE
Folding and outline code in macro definition

### ISSUE THREAD

**Issue by ShuguangSun** [sassoftware/vscode-sas-extension#97]
**Is your feature request related to a problem? Please describe.**
Currently the code in a macro defination from `%macro` to `%mend` would not be folded or outlined, even if using the `/*region*/` and `/*endregion*/` staff. It could be helpful to make the code folding and outline working in macro defination for loop macro.

**Describe the solution you'd like**
It could be helpful to make the code folding and outline working in macro defination for loop macro.

**Describe alternatives you've considered**
Or make  `/*region*/` and `/*endregion*/` work in macro definition.

**Additional context**
No.

**Environment**
SAS version 9.4/EG

**Comment by scnwwu** [comment]
Similar to #6

**Comment by scnwwu** [comment]
Tracking in #6, closing this one.
